const APP_VERSION='v0.8.6';
const FPS=30,MAX_IMAGE_DIM=1920,$=id=>document.getElementById(id);
let S={src:null,starless:null,starsOnly:null,mask:null,stars:[],statics:[],movers:[],suppressedStars:[],motionBg:null,motionMask:null,has:0,map:0,cx:.5,cy:.5,strict:.7,max:2200,move:260,rad:2.5,bias:'balanced',fly:.65,travel:1,grow:.12,zoom:.05,dur:10,preview:'final',play:0,raf:0,start:0,last:0};
function cl(x,a,b){return Math.max(a,Math.min(b,x))}
function st(v){const e=$('status');if(e)e.textContent=v}
function wait(ms=20){return new Promise(r=>setTimeout(r,ms))}
function prog(t,p,l){const o=$('ol');if(o)o.style.display='grid';const a=$('olt'),f=$('fill'),b=$('oll');if(a)a.textContent=t;if(f)f.style.width=cl(p,0,100)+'%';if(b)b.textContent=l||'';st(l||t)}
function hide(){const o=$('ol');if(o)o.style.display='none'}
function dims(){const p=$('preset')?.value||'portrait';return p==='landscape'?{w:1920,h:1080,l:'16x9'}:p==='square'?{w:1080,h:1080,l:'1x1'}:{w:1080,h:1920,l:'9x16'}}
function labels(){const pairs=[['strict','sv',v=>v+'%'],['max','xv',v=>v],['move','mv',v=>v],['rad','rv',v=>(v/100).toFixed(1)+'×'],['fly','fv',v=>(v/100).toFixed(2)+'×'],['travel','yv',v=>(v/100).toFixed(2)+'×'],['grow','gv',v=>(v/100).toFixed(2)+'×'],['zoom','zv',v=>v+'%'],['dur','tv',v=>v+'s']];for(const [id,out,fn] of pairs){const e=$(id),o=$(out);if(e&&o)o.textContent=fn(Number(e.value))}const d=dims(),x=$('exinfo');if(x)x.textContent=`Export target: ${d.w}×${d.h} at ${FPS} fps · browser may downscale`;const lab=window.DSD_LIVE_VERSION||APP_VERSION,v=document.querySelector('.ver');if(v)v.textContent=lab;const w=document.querySelector('.warn');if(w)w.textContent=`${lab} · Auto-extract and smooth outward travel.`}
function read(){S.strict=Number($('strict')?.value||70)/100;S.max=Number($('max')?.value||2200);S.move=Number($('move')?.value||260);S.rad=Number($('rad')?.value||250)/100;S.bias=$('bias')?.value||'balanced';S.preview=$('preview')?.value||'final';S.fly=Number($('fly')?.value||65)/100;S.travel=Number($('travel')?.value||100)/100;S.grow=Number($('grow')?.value||12)/100;S.zoom=Number($('zoom')?.value||5)/100;S.dur=Number($('dur')?.value||10);labels()}
function size(w,h){const v=document.querySelector('.view'),c=$('main');if(!v||!c)return;const vw=Math.max(1,v.clientWidth-2),vh=Math.max(1,v.clientHeight-2),a=w/h;let cw,ch;if(vw/vh>a){ch=vh;cw=ch*a}else{cw=vw;ch=cw/a}c.width=Math.max(1,Math.round(cw));c.height=Math.max(1,Math.round(ch));c.style.display='block'}
function fit(img,W,H,cover=false,t=0){const z=1+(S.zoom||0)*(((t||0)/Math.max(1,S.dur||10))%1),ia=img.width/img.height,oa=W/H;let dw,dh;if(cover?oa>ia:oa<ia){dw=W*z;dh=W/ia*z}else{dh=H*z;dw=H*ia*z}let x=(W-dw)/2,y=(H-dh)/2;if(cover||z>1){x=cl(W/2-(S.cx??.5)*dw,W-dw,0);y=cl(H/2-(S.cy??.5)*dh,H-dh,0)}return{x,y,w:dw,h:dh}}
function base(c,t=0,mode='contain'){if(!S.src||!c)return;const g=c.getContext('2d'),r=fit(S.src,c.width,c.height,mode==='cover',t);g.fillStyle='#000';g.fillRect(0,0,c.width,c.height);g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(S.src,r.x,r.y,r.w,r.h)}
function render(t=0){if(!S.src)return;read();const c=$('main');size(S.src.width,S.src.height);base(c,t,'contain');S.last=t||0}
function autoExtract(){window.DSD_PENDING_AUTO_EXTRACT=true;let tries=0;const go=()=>{if(!S.src||S.map)return;if(window.DSD_DRAW_FRAME&&typeof build==='function'){window.DSD_PENDING_AUTO_EXTRACT=false;build();return}if(tries++<60)setTimeout(go,100)};setTimeout(go,120)}
async function load(file){if(!file)return;const url=URL.createObjectURL(file),im=new Image;im.onload=()=>{URL.revokeObjectURL(url);let w=im.naturalWidth,h=im.naturalHeight,ow=w,oh=h;if(Math.max(w,h)>MAX_IMAGE_DIM){const s=MAX_IMAGE_DIM/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);Object.assign(S,{src:c,starless:null,starsOnly:null,mask:null,stars:[],statics:[],movers:[],suppressedStars:[],motionBg:null,motionMask:null,has:1,map:0,cx:.5,cy:.5,play:0,start:0,last:0});const d=$('drop');if(d)d.style.display='none';const b=$('build');if(b){b.disabled=false;b.textContent='Extracting Stars…'}const p=$('play');if(p)p.disabled=true;const e=$('export');if(e)e.disabled=true;const s=$('stats');if(s){s.style.display='none';s.textContent=''}const dim=$('dim');if(dim)dim.textContent=ow===w&&oh===h?`${w}×${h}`:`${ow}×${oh}→${w}×${h}`;size(w,h);render(0);st('Image loaded · extracting stars…');autoExtract()};im.onerror=()=>{URL.revokeObjectURL(url);st('Could not load image')};im.src=url}
async function build(){st('Star engine is still loading. Try again in a moment.')}
function play(){if(!S.map)return;S.play=!S.play;const b=$('play');if(S.play){if(b)b.textContent='⏸ Pause';S.start=0;loop(performance.now())}else{if(b)b.textContent='▶ Play';cancelAnimationFrame(S.raf)}}
function loop(ts){if(!S.play)return;if(!S.start)S.start=ts-(S.last||0)*1000;render((ts-S.start)/1000);S.raf=requestAnimationFrame(loop)}
async function exp(){if(!S.map||!window.MediaRecorder)return;read();if(S.play)play();const mt=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mt){st('No supported recording format found.');return}const d=dims(),ext=mt.includes('mp4')?'mp4':'webm',c=document.createElement('canvas');c.width=d.w;c.height=d.h;c.style.cssText=`position:fixed;left:0;top:0;width:${d.w}px;height:${d.h}px;opacity:0.01;pointer-events:none;background:#000;z-index:9999`;document.body.appendChild(c);const old=S.preview;S.preview='final';const draw=window.DSD_DRAW_FRAME||((cv,t)=>base(cv,t,'cover'));const eb=$('export'),pb=$('play');if(eb)eb.disabled=true;if(pb)pb.disabled=true;draw(c,0,'cover');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let stream;try{stream=c.captureStream(0)}catch(e){stream=c.captureStream(FPS)}const track=stream.getVideoTracks()[0],rec=new MediaRecorder(stream,{mimeType:mt,videoBitsPerSecond:18000000}),chunks=[];rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};const done=new Promise(r=>rec.onstop=r),frames=Math.max(1,Math.round((S.dur||10)*FPS)),ms=1000/FPS,start=performance.now();prog('Exporting movie',0,`${d.w}×${d.h} · ${S.dur}s · ${APP_VERSION}`);rec.start(250);for(let f=0;f<frames;f++){const target=start+f*ms,now=performance.now();if(target>now)await wait(Math.max(0,target-now));const seconds=f/FPS;draw(c,seconds,'cover');track&&track.requestFrame&&track.requestFrame();if(f%15===0||f===frames-1){const pct=Math.round((f+1)/frames*100);prog('Exporting movie',pct,`${pct}% · deterministic ${FPS} fps draw`)}}await wait(140);rec.stop();await done;S.preview=old;document.body.removeChild(c);const blob=new Blob(chunks,{type:mt}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`deepsky-drift-${APP_VERSION}-${d.l}-${S.dur}s.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000);hide();if(eb)eb.disabled=false;if(pb)pb.disabled=false;render(S.last||0);st(`Download ready · ${APP_VERSION}`)}
function center(e){if(!S.src)return;const c=$('main');if(!c)return;const r=c.getBoundingClientRect();if(!r.width||!r.height)return;const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(x<0||x>1||y<0||y>1)return;S.cx=cl(x,.04,.96);S.cy=cl(y,.04,.96);render(S.last||0);st('Zoom center set')}
function wire(){labels();const browse=$('browse');if(browse)browse.onclick=()=>$('file')&&$('file').click();const file=$('file');if(file)file.onchange=e=>load(e.target.files[0]);const drop=$('drop');if(drop){drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();load(e.dataTransfer.files[0])}}const b=$('build');if(b)b.onclick=()=>build();const p=$('play');if(p)p.onclick=()=>play();const ex=$('export');if(ex)ex.onclick=()=>exp();const reset=$('reset');if(reset)reset.onclick=()=>location.reload();for(const id of ['strict','max','rad','fly','travel','grow','zoom','dur']){const e=$(id);if(e)e.oninput=()=>{read();render(S.last||0)}}const mv=$('move');if(mv)mv.oninput=()=>{read();if(window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS()};const bias=$('bias');if(bias)bias.oninput=()=>{read();if(window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS()};const prev=$('preview');if(prev)prev.oninput=()=>{read();render(S.last||0)};const preset=$('preset');if(preset)preset.oninput=()=>{read();render(S.last||0)};const view=document.querySelector('.view');if(view)view.addEventListener('pointerdown',center,{passive:true});window.onresize=()=>S.src&&render(S.last||0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
