const APP_VERSION='v0.8.7';
const FPS=30,MAX_IMAGE_DIM=1920,$=id=>document.getElementById(id);
let S={src:null,starless:null,starsOnly:null,mask:null,stars:[],statics:[],movers:[],suppressedStars:[],motionBg:null,motionMask:null,has:0,map:0,cx:.5,cy:.5,strict:.7,max:2200,move:260,rad:2.5,bias:'balanced',fly:.65,travel:1,grow:.12,zoom:.05,dur:10,preview:'final',play:0,raf:0,start:0,last:0,loadCount:0,lastExportBlob:null,lastExportName:null,lastPreset:'Cinematic Drift'};
const PRESETS={cinematic:{name:'Cinematic Drift',strict:70,max:2200,move:260,rad:250,bias:'balanced',fly:65,travel:100,grow:12,zoom:5,dur:10,preset:'portrait'},flythrough:{name:'Deep Space Flythrough',strict:66,max:3200,move:520,rad:255,bias:'balanced',fly:115,travel:180,grow:16,zoom:7,dur:10,preset:'portrait'},meditation:{name:'Gentle Meditation',strict:74,max:1800,move:180,rad:245,bias:'isolated',fly:38,travel:45,grow:6,zoom:3,dur:60,preset:'landscape'},social:{name:'Social Reel',strict:68,max:2600,move:420,rad:250,bias:'bright',fly:90,travel:145,grow:14,zoom:6,dur:15,preset:'portrait'},galaxy:{name:'Galaxy Core Push',strict:72,max:2200,move:240,rad:245,bias:'isolated',fly:75,travel:115,grow:8,zoom:6,dur:20,preset:'landscape'}};
const INTENSITY={subtle:{fly:42,travel:60,grow:5,move:180},cinematic:{fly:75,travel:115,grow:10,move:300},intense:{fly:125,travel:210,grow:16,move:560}};
function cl(x,a,b){return Math.max(a,Math.min(b,x))}
function st(v){const e=$('status');if(e)e.textContent=v}
function wait(ms=20){return new Promise(r=>setTimeout(r,ms))}
function ga(name,params={}){try{if(window.trackGA4)window.trackGA4(name,Object.assign({app_version:APP_VERSION},params||{}))}catch(e){}}
function prog(t,p,l){const o=$('ol');if(o)o.style.display='grid';const a=$('olt'),f=$('fill'),b=$('oll');if(a)a.textContent=t;if(f)f.style.width=cl(p,0,100)+'%';if(b)b.textContent=l||'';st(l||t)}
function hide(){const o=$('ol');if(o)o.style.display='none'}
function dims(){const p=$('preset')?.value||'portrait';return p==='landscape'?{w:1920,h:1080,l:'16x9'}:p==='square'?{w:1080,h:1080,l:'1x1'}:{w:1080,h:1920,l:'9x16'}}
function setVal(id,v){const e=$(id);if(e)e.value=String(v)}
function labels(){const pairs=[['strict','sv',v=>v+'%'],['max','xv',v=>v],['move','mv',v=>v],['rad','rv',v=>(v/100).toFixed(1)+'×'],['fly','fv',v=>(v/100).toFixed(2)+'×'],['travel','yv',v=>(v/100).toFixed(2)+'×'],['grow','gv',v=>(v/100).toFixed(2)+'×'],['zoom','zv',v=>v+'%'],['dur','tv',v=>v+'s']];for(const [id,out,fn] of pairs){const e=$(id),o=$(out);if(e&&o)o.textContent=fn(Number(e.value))}const d=dims(),x=$('exinfo');if(x)x.textContent=`Export target: ${d.w}×${d.h} at ${FPS} fps · browser may downscale`;const lab=window.DSD_LIVE_VERSION||APP_VERSION,v=document.querySelector('.ver');if(v)v.textContent=lab;const w=document.querySelector('.warn');if(w)w.textContent=`${lab} · ${S.lastPreset||'Magic presets'} ready.`}
function read(){S.strict=Number($('strict')?.value||70)/100;S.max=Number($('max')?.value||2200);S.move=Number($('move')?.value||260);S.rad=Number($('rad')?.value||250)/100;S.bias=$('bias')?.value||'balanced';S.preview=$('preview')?.value||'final';S.fly=Number($('fly')?.value||65)/100;S.travel=Number($('travel')?.value||100)/100;S.grow=Number($('grow')?.value||12)/100;S.zoom=Number($('zoom')?.value||5)/100;S.dur=Number($('dur')?.value||10);labels()}
function size(w,h){const v=document.querySelector('.view'),c=$('main');if(!v||!c)return;const vw=Math.max(1,v.clientWidth-2),vh=Math.max(1,v.clientHeight-2),a=w/h;let cw,ch;if(vw/vh>a){ch=vh;cw=ch*a}else{cw=vw;ch=cw/a}c.width=Math.max(1,Math.round(cw));c.height=Math.max(1,Math.round(ch));c.style.display='block'}
function fit(img,W,H,cover=false,t=0){const z=1+(S.zoom||0)*(((t||0)/Math.max(1,S.dur||10))%1),ia=img.width/img.height,oa=W/H;let dw,dh;if(cover?oa>ia:oa<ia){dw=W*z;dh=W/ia*z}else{dh=H*z;dw=H*ia*z}let x=(W-dw)/2,y=(H-dh)/2;if(cover||z>1){x=cl(W/2-(S.cx??.5)*dw,W-dw,0);y=cl(H/2-(S.cy??.5)*dh,H-dh,0)}return{x,y,w:dw,h:dh}}
function base(c,t=0,mode='contain'){if(!S.src||!c)return;const g=c.getContext('2d'),r=fit(S.src,c.width,c.height,mode==='cover',t);g.fillStyle='#000';g.fillRect(0,0,c.width,c.height);g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(S.src,r.x,r.y,r.w,r.h)}
function render(t=0){if(!S.src)return;read();const c=$('main');size(S.src.width,S.src.height);base(c,t,'contain');S.last=t||0}
function autoCenter(){if(!S.src)return;try{const w=S.src.width,h=S.src.height,g=S.src.getContext('2d',{willReadFrequently:true}),data=g.getImageData(0,0,w,h).data;let hist=new Array(64).fill(0);for(let i=0;i<data.length;i+=16){const L=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];hist[Math.min(63,L>>2)]++}let total=hist.reduce((a,b)=>a+b,0),acc=0,bin=50;for(let i=63;i>=0;i--){acc+=hist[i];if(acc>total*.015){bin=i;break}}const thr=Math.max(35,bin*4);let sx=0,sy=0,sw=0;for(let y=0,p=0;y<h;y++){for(let x=0;x<w;x++,p+=4){const L=.2126*data[p]+.7152*data[p+1]+.0722*data[p+2];if(L>=thr&&L<245){const wt=(L-thr+1)*(1-Math.abs(x/w-.5)*.25)*(1-Math.abs(y/h-.5)*.25);sx+=x*wt;sy+=y*wt;sw+=wt}}}if(sw>0){S.cx=cl(sx/sw/w,.08,.92);S.cy=cl(sy/sw/h,.08,.92);const e=$('centerNote');if(e)e.textContent=`Auto center set: ${(S.cx*100).toFixed(0)}%, ${(S.cy*100).toFixed(0)}%. Tap preview to aim.`;ga('auto_center_set',{cx:Number(S.cx.toFixed(3)),cy:Number(S.cy.toFixed(3))})}}catch(e){}}
function applyPreset(key,source='user'){const p=PRESETS[key];if(!p)return;setVal('strict',p.strict);setVal('max',p.max);setVal('move',p.move);setVal('rad',p.rad);setVal('bias',p.bias);setVal('fly',p.fly);setVal('travel',p.travel);setVal('grow',p.grow);setVal('zoom',p.zoom);setVal('dur',p.dur);setVal('preset',p.preset);S.lastPreset=p.name;document.querySelectorAll('[data-preset-key]').forEach(b=>b.classList.toggle('active',b.dataset.presetKey===key));read();if(S.map&&window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS();else if(S.src)render(S.last||0);st(`${p.name} preset applied`);ga('preset_selected',{preset:p.name,source})}
function applyIntensity(key){const p=INTENSITY[key];if(!p)return;setVal('fly',p.fly);setVal('travel',p.travel);setVal('grow',p.grow);setVal('move',p.move);read();if(S.map&&window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS();else if(S.src)render(S.last||0);ga('intensity_selected',{intensity:key});st(`${key[0].toUpperCase()+key.slice(1)} motion applied`)}
function showSuccess(name){const s=$('success');if(!s)return;s.style.display='block';const n=$('successName');if(n)n.textContent=name||S.lastExportName||'movie';ga('export_panel_shown')}
function hideSuccess(){const s=$('success');if(s)s.style.display='none'}
async function shareLast(){ga('share_clicked',{has_blob:!!S.lastExportBlob});try{if(S.lastExportBlob&&navigator.share){const file=new File([S.lastExportBlob],S.lastExportName||'deepsky-drift.mp4',{type:S.lastExportBlob.type||'video/mp4'});if(!navigator.canShare||navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'DeepSkyDrift',text:'I made my astrophotography image move with DeepSkyDrift'});return}}if(navigator.share){await navigator.share({title:'DeepSkyDrift',text:'Create motion videos from astrophotography images',url:location.href});return}await navigator.clipboard.writeText(location.href);st('Link copied')}catch(e){st('Share canceled or unavailable')}}
function autoExtract(){window.DSD_PENDING_AUTO_EXTRACT=true;let tries=0;const go=()=>{if(!S.src||S.map)return;if(window.DSD_DRAW_FRAME&&typeof build==='function'){window.DSD_PENDING_AUTO_EXTRACT=false;build();return}if(tries++<60)setTimeout(go,100)};setTimeout(go,120)}
async function load(file){if(!file)return;const url=URL.createObjectURL(file),im=new Image;im.onload=()=>{URL.revokeObjectURL(url);let w=im.naturalWidth,h=im.naturalHeight,ow=w,oh=h;if(Math.max(w,h)>MAX_IMAGE_DIM){const s=MAX_IMAGE_DIM/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);S.loadCount=(S.loadCount||0)+1;Object.assign(S,{src:c,starless:null,starsOnly:null,mask:null,stars:[],statics:[],movers:[],suppressedStars:[],motionBg:null,motionMask:null,has:1,map:0,cx:.5,cy:.5,play:0,start:0,last:0});hideSuccess();autoCenter();const d=$('drop');if(d)d.style.display='none';const b=$('build');if(b){b.disabled=false;b.textContent='Extracting Stars…'}const p=$('play');if(p)p.disabled=true;const e=$('export');if(e)e.disabled=true;const s=$('stats');if(s){s.style.display='none';s.textContent=''}const dim=$('dim');if(dim)dim.textContent=ow===w&&oh===h?`${w}×${h}`:`${ow}×${oh}→${w}×${h}`;size(w,h);render(0);st('Image loaded · extracting stars…');ga('image_loaded',{load_number:S.loadCount});if(S.loadCount>1)ga('second_image_loaded',{load_number:S.loadCount});autoExtract()};im.onerror=()=>{URL.revokeObjectURL(url);st('Could not load image')};im.src=url}
async function build(){st('Star engine is still loading. Try again in a moment.')}
function play(){if(!S.map)return;S.play=!S.play;const b=$('play');if(S.play){if(b)b.textContent='⏸ Pause';S.start=0;loop(performance.now());ga('preview_play')}else{if(b)b.textContent='▶ Play';cancelAnimationFrame(S.raf)}}
function loop(ts){if(!S.play)return;if(!S.start)S.start=ts-(S.last||0)*1000;render((ts-S.start)/1000);S.raf=requestAnimationFrame(loop)}
async function exp(){if(!S.map||!window.MediaRecorder)return;read();if(S.play)play();ga('export_started',{duration:S.dur,aspect:dims().l,preset:S.lastPreset||''});const mt=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mt){st('No supported recording format found.');return}const d=dims(),ext=mt.includes('mp4')?'mp4':'webm',c=document.createElement('canvas');c.width=d.w;c.height=d.h;c.style.cssText=`position:fixed;left:0;top:0;width:${d.w}px;height:${d.h}px;opacity:0.01;pointer-events:none;background:#000;z-index:9999`;document.body.appendChild(c);const old=S.preview;S.preview='final';const draw=window.DSD_DRAW_FRAME||((cv,t)=>base(cv,t,'cover'));const eb=$('export'),pb=$('play');if(eb)eb.disabled=true;if(pb)pb.disabled=true;draw(c,0,'cover');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let stream;try{stream=c.captureStream(0)}catch(e){stream=c.captureStream(FPS)}const trackObj=stream.getVideoTracks()[0],rec=new MediaRecorder(stream,{mimeType:mt,videoBitsPerSecond:18000000}),chunks=[];rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};const done=new Promise(r=>rec.onstop=r),frames=Math.max(1,Math.round((S.dur||10)*FPS)),ms=1000/FPS,start=performance.now();prog('Exporting movie',0,`${d.w}×${d.h} · ${S.dur}s · ${APP_VERSION}`);rec.start(250);for(let f=0;f<frames;f++){const target=start+f*ms,now=performance.now();if(target>now)await wait(Math.max(0,target-now));const seconds=f/FPS;draw(c,seconds,'cover');trackObj&&trackObj.requestFrame&&trackObj.requestFrame();if(f%15===0||f===frames-1){const pct=Math.round((f+1)/frames*100);prog('Exporting movie',pct,`${pct}% · deterministic ${FPS} fps draw`)}}await wait(140);rec.stop();await done;S.preview=old;document.body.removeChild(c);const blob=new Blob(chunks,{type:mt}),u=URL.createObjectURL(blob),a=document.createElement('a'),fname=`deepsky-drift-${APP_VERSION}-${d.l}-${S.dur}s.${ext}`;S.lastExportBlob=blob;S.lastExportName=fname;a.href=u;a.download=fname;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000);hide();if(eb)eb.disabled=false;if(pb)pb.disabled=false;render(S.last||0);showSuccess(fname);st(`Download ready · ${APP_VERSION}`);ga('export_completed',{duration:S.dur,aspect:d.l,bytes:blob.size})}
function center(e){if(!S.src)return;const c=$('main');if(!c)return;const r=c.getBoundingClientRect();if(!r.width||!r.height)return;const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(x<0||x>1||y<0||y>1)return;S.cx=cl(x,.04,.96);S.cy=cl(y,.04,.96);render(S.last||0);const n=$('centerNote');if(n)n.textContent=`Center set: ${(S.cx*100).toFixed(0)}%, ${(S.cy*100).toFixed(0)}%`;ga('center_set',{cx:Number(S.cx.toFixed(3)),cy:Number(S.cy.toFixed(3))});st('Zoom center set')}
function wire(){labels();applyPreset('cinematic','default');const browse=$('browse');if(browse)browse.onclick=()=>$('file')&&$('file').click();const file=$('file');if(file)file.onchange=e=>load(e.target.files[0]);const drop=$('drop');if(drop){drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();load(e.dataTransfer.files[0])}}const b=$('build');if(b)b.onclick=()=>build();const p=$('play');if(p)p.onclick=()=>play();const ex=$('export');if(ex)ex.onclick=()=>exp();const reset=$('reset');if(reset)reset.onclick=()=>location.reload();document.querySelectorAll('[data-preset-key]').forEach(btn=>btn.onclick=()=>applyPreset(btn.dataset.presetKey));document.querySelectorAll('[data-intensity]').forEach(btn=>btn.onclick=()=>applyIntensity(btn.dataset.intensity));const another=$('again');if(another)another.onclick=()=>{$('file')&&$('file').click();ga('create_another_clicked')};const share=$('share');if(share)share.onclick=()=>shareLast();const vertical=$('makeVertical');if(vertical)vertical.onclick=()=>{setVal('preset','portrait');read();ga('export_variant_clicked',{variant:'portrait'});exp()};const slow=$('makeSlow');if(slow)slow.onclick=()=>{applyPreset('meditation','success_panel');ga('export_variant_clicked',{variant:'meditation'});exp()};for(const id of ['strict','max','rad','fly','travel','grow','zoom','dur']){const e=$(id);if(e)e.oninput=()=>{read();render(S.last||0)}}const mv=$('move');if(mv)mv.oninput=()=>{read();if(window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS()};const bias=$('bias');if(bias)bias.oninput=()=>{read();if(window.DSD_RESELECT_MOVERS)window.DSD_RESELECT_MOVERS()};const prev=$('preview');if(prev)prev.oninput=()=>{read();render(S.last||0)};const preset=$('preset');if(preset)preset.oninput=()=>{read();render(S.last||0)};const view=document.querySelector('.view');if(view)view.addEventListener('pointerdown',center,{passive:true});window.onresize=()=>S.src&&render(S.last||0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
