(function(){
'use strict';
const ENGINE_VERSION='v0.8.4';
window.DSD_LIVE_VERSION=ENGINE_VERSION;
const $=id=>document.getElementById(id);
const cl=(x,a,b)=>Math.max(a,Math.min(b,x));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
function ok(){try{return typeof S!=='undefined'&&S&&S.src}catch(e){return false}}
function txt(id,v){const e=$(id);if(e)e.textContent=v}
function status(v){txt('status',v)}
function prog(t,p,l){const o=$('ol');if(o)o.style.display='grid';txt('olt',t);const f=$('fill');if(f)f.style.width=cl(p,0,100)+'%';txt('oll',l||'');status(l||t)}
function hide(){const o=$('ol');if(o)o.style.display='none'}
function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function ctx(c){return c.getContext('2d',{willReadFrequently:true})}
function ui(){const v=document.querySelector('.ver');if(v)v.textContent=ENGINE_VERSION;const b=$('badge');if(b)b.textContent=ENGINE_VERSION+' · repaired moving-star background';const w=document.querySelector('.warn');if(w)w.textContent=ENGINE_VERSION+' · Moving stars are locally removed from the background. Original target structure is protected.';const build=$('build');if(build&&!build.disabled)build.textContent=S&&S.map?'Re-extract Stars':'Extract Stars'}
function read(){if(!ok())return;const n=(id,d,s=1)=>{const e=$(id),v=e?Number(e.value):NaN;return Number.isFinite(v)?v*s:d};S.strict=n('strict',S.strict??.7,.01);S.max=Math.round(n('max',S.max||2200));S.move=Math.round(n('move',S.move||260));S.rad=n('rad',S.rad||2.5,.01);S.fly=n('fly',S.fly||.65,.01);S.grow=n('grow',S.grow||.12,.01);S.zoom=n('zoom',S.zoom||.05,.01);S.dur=n('dur',S.dur||10);const p=$('preview');if(p)S.preview=p.value;const b=$('bias');if(b)S.bias=b.value}
function lum(data){const out=new Float32Array(data.length/4);for(let i=0,p=0;i<out.length;i++,p+=4)out[i]=(.2126*data[p]+.7152*data[p+1]+.0722*data[p+2])/255;return out}
function blur(a,w,h,r){r=Math.max(1,r|0);const t=new Float32Array(w*h),o=new Float32Array(w*h),win=r*2+1;for(let y=0;y<h;y++){const row=y*w;let s=0;for(let dx=-r;dx<=r;dx++)s+=a[row+cl(dx,0,w-1)];for(let x=0;x<w;x++){t[row+x]=s/win;s+=a[row+cl(x+r+1,0,w-1)]-a[row+cl(x-r,0,w-1)]}}for(let x=0;x<w;x++){let s=0;for(let dy=-r;dy<=r;dy++)s+=t[cl(dy,0,h-1)*w+x];for(let y=0;y<h;y++){o[y*w+x]=s/win;s+=t[cl(y+r+1,0,h-1)*w+x]-t[cl(y-r,0,h-1)*w+x]}}return o}
function positiveStats(a){let n=0,s=0,s2=0;for(const v of a){if(v<=0)continue;n++;s+=v;s2+=v*v}if(!n)return{mean:0,rms:.001};const m=s/n;return{mean:m,rms:Math.sqrt(Math.max(1e-8,s2/n-m*m))}}
function detectStars(src){const scale=Math.max(src.width,src.height)>1300?.5:1,W=Math.max(1,Math.round(src.width*scale)),H=Math.max(1,Math.round(src.height*scale)),c=canvas(W,H);ctx(c).drawImage(src,0,0,W,H);const data=ctx(c).getImageData(0,0,W,H).data,L=lum(data),bg=blur(L,W,H,Math.max(10,Math.round(Math.min(W,H)/90))),sm=blur(L,W,H,1),dog=new Float32Array(W*H);for(let i=0;i<dog.length;i++)dog[i]=Math.max(0,sm[i]-bg[i]);const st=positiveStats(dog),strict=cl(S.strict??.7,.25,.98),threshold=st.mean+st.rms*(1.05+strict*2.7),grow=threshold*.48,seen=new Uint8Array(W*H),dirs=[1,-1,W,-W,W+1,W-1,-W+1,-W-1],stars=[];let id=1;for(let i=0;i<dog.length;i++){if(seen[i]||dog[i]<threshold)continue;const q=[i],pix=[];seen[i]=1;while(q.length){const p=q.pop();pix.push(p);const x=p%W,y=p/W|0;for(const d of dirs){const np=p+d;if(np<0||np>=dog.length||seen[np])continue;const nx=np%W,ny=np/W|0;if(Math.abs(nx-x)>1||Math.abs(ny-y)>1)continue;if(dog[np]<grow)continue;seen[np]=1;q.push(np)}}const area=pix.length;if(area<1||area>260)continue;let minx=W,maxx=0,miny=H,maxy=0,flux=0,peak=0,sx=0,sy=0,bgs=0;for(const p of pix){const x=p%W,y=p/W|0,v=dog[p],wt=Math.max(v,1e-6);flux+=v;peak=Math.max(peak,v);sx+=x*wt;sy+=y*wt;bgs+=bg[p];minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y)}if(flux<=0)continue;const cx=sx/flux,cy=sy/flux,bw=maxx-minx+1,bh=maxy-miny+1,aspect=Math.max(bw,bh)/Math.max(1,Math.min(bw,bh)),r=Math.sqrt(area/Math.PI);if(bw>28||bh>28||aspect>2.55&&area>5)continue;let ann=0,annn=0,rr=Math.max(6,r*4.5);for(let yy=Math.floor(cy-rr);yy<=cy+rr;yy++){if(yy<0||yy>=H)continue;for(let xx=Math.floor(cx-rr);xx<=cx+rr;xx++){if(xx<0||xx>=W)continue;const dd=Math.hypot(xx-cx,yy-cy);if(dd<r*2||dd>rr)continue;ann+=dog[yy*W+xx];annn++}}const iso=peak/Math.max(st.rms*.2,(annn?ann/annn:0)+st.rms*.18),compact=peak/Math.max(1e-6,flux/area),localBg=bgs/area;if(iso<(area>50?1.25:1.45)||compact<1.35&&area>8)continue;if(localBg>.24&&peak<st.rms*7.5)continue;stars.push({id:'star-'+id++,x:cx/scale,y:cy/scale,r:Math.max(1.1,r/scale),area,bboxW:bw/scale,bboxH:bh/scale,peak,flux,isolation:iso,compactness:compact,bg:localBg,score:peak*3.2+Math.sqrt(flux)*.5+r*.06+iso*.04})}stars.sort((a,b)=>b.score-a.score);return stars.slice(0,Math.min(Math.max(S.max||2200,(S.move||260)*4,800),stars.length))}
function tiers(stars){const sorted=stars.slice().sort((a,b)=>b.score-a.score),n=Math.max(1,sorted.length),rank=new Map;sorted.forEach((s,i)=>rank.set(s.id,i/n));for(const s of stars){const q=rank.get(s.id);if(q<=.15||s.r>4.8||s.peak>.22){s.tier=3;s.depth=1.18;s.speed=1}else if(q<=.5||s.r>2.5){s.tier=2;s.depth=.82;s.speed=1}else{s.tier=1;s.depth=.5;s.speed=1}}}
function makeMask(W,H,stars){const m=new Float32Array(W*H),rf=cl(S.rad||2.5,1.2,4.8);for(const s of stars){const halo=s.tier===3?1.22:s.tier===2?1.08:.95,r=Math.max(2.2,s.r*rf*halo);s.maskRadius=r;for(let y=Math.floor(s.y-r);y<=s.y+r;y++){if(y<0||y>=H)continue;for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||x>=W)continue;const d=Math.hypot(x-s.x,y-s.y);if(d>r)continue;let a=1-cl((d-r*.25)/Math.max(1e-5,r*.75),0,1);a=a*a*(3-2*a);const k=y*W+x;if(a>m[k])m[k]=a}}}return m}
function maskCanvas(m,W,H){const c=canvas(W,H),x=ctx(c),id=x.createImageData(W,H);for(let i=0,p=0;i<m.length;i++,p+=4){const v=cl(m[i]*255,0,255)|0;id.data[p]=id.data[p+1]=id.data[p+2]=v;id.data[p+3]=255}x.putImageData(id,0,0);return c}
function copyCanvas(src){const c=canvas(src.width,src.height);ctx(c).drawImage(src,0,0);return c}
function starsOnly(src,m){const W=src.width,H=src.height,c=canvas(W,H),x=ctx(c),s=ctx(src).getImageData(0,0,W,H).data,id=x.createImageData(W,H);for(let i=0,p=0;i<m.length;i++,p+=4){const a=cl(m[i],0,1);if(a<=.006)continue;id.data[p]=s[p];id.data[p+1]=s[p+1];id.data[p+2]=s[p+2];id.data[p+3]=cl(a*255,0,255)|0}x.putImageData(id,0,0);return c}
function sprites(src,m,stars){const W=src.width,H=src.height,s=ctx(src).getImageData(0,0,W,H).data;for(const star of stars){const r=Math.max(4,(star.maskRadius||star.r*2.5)*1.05),x0=cl(Math.floor(star.x-r),0,W-1),y0=cl(Math.floor(star.y-r),0,H-1),x1=cl(Math.ceil(star.x+r+1),1,W),y1=cl(Math.ceil(star.y+r+1),1,H),sw=Math.max(1,x1-x0),sh=Math.max(1,y1-y0),c=canvas(sw,sh),cx=ctx(c),id=cx.createImageData(sw,sh);for(let yy=0;yy<sh;yy++)for(let xx=0;xx<sw;xx++){const sx=x0+xx,sy=y0+yy,si=sy*W+sx,a=cl(m[si],0,1);if(a<=.006)continue;const sp=si*4,dp=(yy*sw+xx)*4;id.data[dp]=s[sp];id.data[dp+1]=s[sp+1];id.data[dp+2]=s[sp+2];id.data[dp+3]=cl(a*230,0,230)|0}cx.putImageData(id,0,0);star.img=c;star.sp=c;star.ax=star.x-x0;star.ay=star.y-y0;star.w=sw;star.h=sh}}
function score(s,b){if(b==='bright')return s.peak||0;if(b==='size')return s.r||0;if(b==='isolated')return s.isolation||0;return s.score||0}
function choose(stars){const want=Math.min(Math.max(0,S.move||260),stars.length),b=S.bias||'balanced',rank=stars.slice().sort((a,z)=>score(z,b)-score(a,b)),out=[],space=Math.max(2.5,Math.min(S.src.width,S.src.height)/210);for(const s of rank){if(out.length>=want)break;let good=true;for(const t of out){if(Math.hypot(s.x-t.x,s.y-t.y)<Math.max(space,(s.r+t.r)*.35)){good=false;break}}if(good)out.push(s)}for(const s of rank){if(out.length>=want)break;if(!out.includes(s))out.push(s)}return out.slice(0,want)}
function repairRadius(s){const f=s.tier===3?1.85:s.tier===2?1.6:1.4;return cl((s.r||1.4)*f,2.5,14)}
function buildMoverRepairMask(W,H,movers){const m=new Float32Array(W*H);for(const s of movers||[]){const r=repairRadius(s),core=r*.45;s.repairRadius=r;for(let y=Math.floor(s.y-r);y<=s.y+r;y++){if(y<0||y>=H)continue;for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||x>=W)continue;const d=Math.hypot(x-s.x,y-s.y);if(d>r)continue;let a=d<=core?1:1-cl((d-core)/Math.max(1e-5,r-core),0,1);a=a*a*(3-2*a);const k=y*W+x;if(a>m[k])m[k]=a}}}return{a:m,canvas:maskCanvas(m,W,H)}}
function buildSamplingExclusionMask(W,H,stars){const ex=new Uint8Array(W*H);for(const s of stars||[]){const r=cl((s.r||1.2)*2.25,2.4,18);for(let y=Math.floor(s.y-r);y<=s.y+r;y++){if(y<0||y>=H)continue;for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||x>=W)continue;if(Math.hypot(x-s.x,y-s.y)<=r)ex[y*W+x]=1}}}return ex}
function median(vals){if(!vals.length)return 0;const a=vals.slice().sort((x,y)=>x-y),m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])*.5}
function collectSamples(data,W,H,s,ex){const r=s.repairRadius||repairRadius(s),rin=r*1.35,rout=r*3.1,raw=[];for(let y=Math.floor(s.y-rout);y<=s.y+rout;y++){if(y<0||y>=H)continue;for(let x=Math.floor(s.x-rout);x<=s.x+rout;x++){if(x<0||x>=W)continue;const d=Math.hypot(x-s.x,y-s.y);if(d<rin||d>rout)continue;if(ex&&ex[y*W+x])continue;const k=(y*W+x)*4,R=data[k],G=data[k+1],B=data[k+2],L=.2126*R+.7152*G+.0722*B;raw.push({x,y,nx:(x-s.x)/rout,ny:(y-s.y)/rout,r:R,g:G,b:B,l:L})}}if(raw.length<8)return raw;const med=median(raw.map(p=>p.l)),mad=median(raw.map(p=>Math.abs(p.l-med)))||1,limit=med+4.2*mad+10;return raw.filter(p=>p.l<=limit)}
function solve3(a00,a01,a02,a11,a12,a22,b0,b1,b2){const det=a00*(a11*a22-a12*a12)-a01*(a01*a22-a12*a02)+a02*(a01*a12-a11*a02);if(Math.abs(det)<1e-8)return null;const d0=b0*(a11*a22-a12*a12)-a01*(b1*a22-a12*b2)+a02*(b1*a12-a11*b2);const d1=a00*(b1*a22-a12*b2)-b0*(a01*a22-a12*a02)+a02*(a01*b2-b1*a02);const d2=a00*(a11*b2-b1*a12)-a01*(a01*b2-b1*a02)+b0*(a01*a12-a11*a02);return[d0/det,d1/det,d2/det]}
function fitPlane(samples,ch){let n=0,sx=0,sy=0,sxx=0,sxy=0,syy=0,sv=0,svx=0,svy=0;for(const p of samples){const x=p.nx,y=p.ny,v=p[ch];n++;sx+=x;sy+=y;sxx+=x*x;sxy+=x*y;syy+=y*y;sv+=v;svx+=v*x;svy+=v*y}if(n<24)return null;return solve3(n,sx,sy,sxx+.001,sxy,syy+.001,sv,svx,svy)}
function fillModel(samples){if(samples.length<8)return null;const med={r:median(samples.map(p=>p.r)),g:median(samples.map(p=>p.g)),b:median(samples.map(p=>p.b))};const pr=fitPlane(samples,'r'),pg=fitPlane(samples,'g'),pb=fitPlane(samples,'b');if(!pr||!pg||!pb)return{kind:'median',med};return{kind:'plane',r:pr,g:pg,b:pb,med}}
function evalModel(m,ch,nx,ny){if(!m)return 0;if(m.kind==='plane'){const p=m[ch];return cl(p[0]+p[1]*nx+p[2]*ny,0,255)}return m.med[ch]}
function structureScore(samples){if(samples.length<8)return 1;let mean=0;for(const p of samples)mean+=p.l;mean/=samples.length;let v=0;for(const p of samples){const d=p.l-mean;v+=d*d}v=Math.sqrt(v/samples.length);return cl(v/(18+mean*.18),0,1)}
function repairMovingStars(src,movers,repair,ex){const W=src.width,H=src.height,out=copyCanvas(src),octx=ctx(out),id=octx.getImageData(0,0,W,H),dst=id.data,orig=new Uint8ClampedArray(dst),mask=repair&&repair.a;if(!mask||!(movers||[]).length)return out;for(const s of movers){const r=s.repairRadius||repairRadius(s),samples=collectSamples(orig,W,H,s,ex),model=fillModel(samples);if(!model)continue;const structure=structureScore(samples),alphaScale=.95-.42*structure,outer=r*3.1;for(let y=Math.floor(s.y-r);y<=s.y+r;y++){if(y<0||y>=H)continue;for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||x>=W)continue;const idx=y*W+x,a=mask[idx];if(a<=.01)continue;const p=idx*4,nx=(x-s.x)/outer,ny=(y-s.y)/outer,alpha=cl(a*alphaScale,0,.96);const fr=evalModel(model,'r',nx,ny),fg=evalModel(model,'g',nx,ny),fb=evalModel(model,'b',nx,ny);dst[p]=orig[p]*(1-alpha)+fr*alpha;dst[p+1]=orig[p+1]*(1-alpha)+fg*alpha;dst[p+2]=orig[p+2]*(1-alpha)+fb*alpha}}}octx.putImageData(id,0,0);return out}
function rebuildMotionBackground(){if(!ok()||!S.stars||!S.movers)return;S.motionMask=buildMoverRepairMask(S.src.width,S.src.height,S.movers);S.sampleExclusionMask=buildSamplingExclusionMask(S.src.width,S.src.height,S.stars);S.motionBg=repairMovingStars(S.src,S.movers,S.motionMask,S.sampleExclusionMask)}
function updateStats(){const st=$('stats');if(st&&S.stars&&S.stars.length){const a=[1,2,3].map(t=>(S.movers||[]).filter(s=>s.tier===t).length);st.style.display='block';st.textContent=`${S.stars.length} stars detected · ${(S.movers||[]).length} moving · repaired background · center parallax tiers ${a[0]}/${a[1]}/${a[2]}`}txt('mv',String((S.movers||[]).length||S.move||0))}
function reselect(){if(!ok()||!S.map||!S.stars.length)return;read();S.movers=choose(S.stars);const ids=new Set(S.movers.map(s=>s.id));S.suppressedStars=S.stars.filter(s=>!ids.has(s.id));S.statics=[];rebuildMotionBackground();updateStats();renderEngine(S.last||0)}
function rect(img,w,h,t){const z=1+(S.zoom||0)*ease(t||0),ia=img.width/img.height,oa=w/h;let bw,bh;if(ia>oa){bh=img.height;bw=bh*oa}else{bw=img.width;bh=bw/oa}const sw=bw/z,sh=bh/z,cx=(S.cx??.5)*img.width,cy=(S.cy??.5)*img.height;return{sx:cl(cx-sw/2,0,Math.max(0,img.width-sw)),sy:cl(cy-sh/2,0,Math.max(0,img.height-sh)),sw,sh}}
function mapxy(x,y,r,w,h){return{x:(x-r.sx)/r.sw*w,y:(y-r.sy)/r.sh*h}}
function loopPhase(t){t=((t||0)%1+1)%1;return 1-Math.abs(1-2*t)}
function tierK(s){const strength=cl(S.fly||.65,.2,1.8),base=s.tier===3?.105:s.tier===2?.065:.032;return base*strength}
function tierAlpha(s,boost){if(boost)return 1;return s.tier===3?.90:s.tier===2?.78:.68}
function centerScaledPosition(s,p){const cx=(S.cx??.5)*S.src.width,cy=(S.cy??.5)*S.src.height,k=tierK(s),scale=1+k*p;return{x:cx+(s.x-cx)*scale,y:cy+(s.y-cy)*scale}}
function drawStar(c,s,r,w,h,t,moving,boost){const img=s.img||s.sp;if(!img)return;let x=s.x,y=s.y,scale=w/r.sw,alpha=tierAlpha(s,boost);if(moving){const p=loopPhase(t),pos=centerScaledPosition(s,p);x=pos.x;y=pos.y;scale*=1+(S.grow||0)*(s.depth||1)*p*.25;alpha*=.88+.12*p}if(boost)scale*=1.25;const p=mapxy(x,y,r,w,h);if(p.x<-220||p.y<-220||p.x>w+220||p.y>h+220)return;c.save();c.globalAlpha*=alpha;c.drawImage(img,p.x-s.ax*scale,p.y-s.ay*scale,s.w*scale,s.h*scale);c.restore()}
function drawList(c,list,r,w,h,t,moving,boost){if(!list||!list.length)return;c.save();if(boost)c.filter='brightness(2.1) contrast(1.15)';for(const s of list)drawStar(c,s,r,w,h,t,moving,boost);c.restore()}
function drawFrame(c,t){if(!ok())return;read();const g=c.getContext('2d'),w=c.width,h=c.height,bg=S.motionBg||S.src,r=rect(bg,w,h,t||0);g.clearRect(0,0,w,h);g.fillStyle='#000';g.fillRect(0,0,w,h);g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(bg,r.sx,r.sy,r.sw,r.sh,0,0,w,h);const sr=rect(S.src,w,h,t||0);drawList(g,S.movers||[],sr,w,h,t||0,true,false)}
function renderEngine(t){read();ui();if(!ok())return;const c=$('main');if(!c)return;try{if(typeof size==='function')size(S.src.width,S.src.height)}catch(e){}const g=c.getContext('2d'),w=c.width,h=c.height,mode=S.preview||'final';g.clearRect(0,0,w,h);g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';if(mode==='mask'&&S.mask&&S.mask.canvas){const r=rect(S.mask.canvas,w,h,0);g.drawImage(S.mask.canvas,r.sx,r.sy,r.sw,r.sh,0,0,w,h);return}if(mode==='starless'&&(S.motionBg||S.starless)){const bg=S.motionBg||S.starless,r=rect(bg,w,h,0);g.drawImage(bg,r.sx,r.sy,r.sw,r.sh,0,0,w,h);return}if(mode==='stars'){g.fillStyle='#000';g.fillRect(0,0,w,h);const r=rect(S.src,w,h,0);drawList(g,S.suppressedStars||[],r,w,h,0,false,true);return}if(mode==='moving'){g.fillStyle='#000';g.fillRect(0,0,w,h);const r=rect(S.src,w,h,0);drawList(g,S.movers||[],r,w,h,.5,false,true);return}drawFrame(c,t||0);S.last=t||0}
async function buildEngine(){if(!ok())return;read();const btn=$('build');if(btn)btn.disabled=true;try{prog('Finding stars',5,'Detecting compact stars…');await sleep(20);const stars=detectStars(S.src);if(!stars.length){hide();status('No stars detected. Lower Star Strictness.');if(btn)btn.disabled=false;return}prog('Classifying stars',25,'Assigning parallax tiers…');await sleep(20);tiers(stars);prog('Creating star mask',42,'Building sprite and diagnostic masks…');await sleep(20);const m=makeMask(S.src.width,S.src.height,stars);prog('Creating star sprites',60,'Extracting original star sprites…');await sleep(20);sprites(S.src,m,stars);S.mask={a:m,canvas:maskCanvas(m,S.src.width,S.src.height)};S.starless=copyCanvas(S.src);S.starsOnly=starsOnly(S.src,m);S.stars=stars;S.movers=choose(stars);const ids=new Set(S.movers.map(s=>s.id));S.suppressedStars=stars.filter(s=>!ids.has(s.id));S.statics=[];prog('Repairing background',82,'Removing selected moving-star footprints…');await sleep(20);rebuildMotionBackground();S.map=1;S.last=0;if(btn){btn.disabled=false;btn.textContent='Re-extract Stars'}const play=$('play');if(play)play.disabled=false;const ex=$('export');if(ex)ex.disabled=false;updateStats();prog('Ready',100,'Repaired background and centered parallax ready');await sleep(20);hide();renderEngine(0);status(`${ENGINE_VERSION} ready · repaired moving-star background · ${S.movers.length} moving stars`);if(window.trackGA4)window.trackGA4('stars_extracted',{engine:ENGINE_VERSION})}catch(err){hide();if(btn)btn.disabled=false;console.error(err);status('Build failed: '+(err&&err.message?err.message:err))}}
function install(){ui();try{build=buildEngine;render=renderEngine}catch(e){}window.DSD_DRAW_FRAME=drawFrame;window.DSD_RESELECT_MOVERS=reselect;const b=$('build');if(b){b.textContent='Extract Stars';b.onclick=()=>buildEngine()}const p=$('preview');if(p&&!p.dataset.v084){p.dataset.v084='1';p.addEventListener('change',()=>renderEngine(S.last||0),true)}for(const id of ['move','bias']){const e=$(id);if(e&&!e.dataset.v084){e.dataset.v084='1';e.addEventListener('input',reselect,true);e.addEventListener('change',reselect,true)}}for(const id of ['fly','grow','zoom','preset']){const e=$(id);if(e&&!e.dataset.v084){e.dataset.v084='1';e.addEventListener('input',()=>{if(ok())renderEngine(S.last||0)},true);e.addEventListener('change',()=>{if(ok())renderEngine(S.last||0)},true)}}if(ok())renderEngine(S.last||0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
