(function(){
const VERSION='v0.7.0',$=id=>document.getElementById(id),cl=(x,a,b)=>Math.max(a,Math.min(b,x)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function ok(){try{return typeof S!='undefined'&&S&&S.src}catch(e){return false}}function ez(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}function st(t){let e=$('status');if(e)e.textContent=t}function ver(){let e=document.querySelector('.ver');if(e)e.textContent=VERSION;let b=$('badge');if(b)b.textContent=VERSION+' · layered motion engine';let w=document.querySelector('.warn');if(w)w.textContent='v0.7.0 · Layered motion engine.'}function prog(t,p,l){let o=$('ol');if(o)o.style.display='grid';if($('olt'))$('olt').textContent=t;if($('fill'))$('fill').style.width=cl(p,0,100)+'%';if($('oll'))$('oll').textContent=l||'';st(l||t)}function hide(){let o=$('ol');if(o)o.style.display='none'}function stop(){try{S.play=0;cancelAnimationFrame(S.raf)}catch(e){}let b=$('play');if(b)b.textContent='▶ Play'}
function labels(){let p=$('preview');if(p)Array.from(p.options).forEach(o=>{if(o.value==='final')o.text='Final Preview';if(o.value==='starless')o.text='Clean Background';if(o.value==='stars')o.text='Static Stars';if(o.value==='moving')o.text='Stars That Move';if(o.value==='mask')o.text='Star Mask'})}
function marker(){let v=document.querySelector('.view');if(!v)return null;let t=v.querySelector('.target');if(t)return t;t=document.createElement('div');t.className='target';t.style.cssText='position:absolute;width:22px;height:22px;margin-left:-11px;margin-top:-11px;border:2px solid rgba(255,255,255,.95);border-radius:50%;pointer-events:none;display:none;z-index:4';let a=document.createElement('div'),b=document.createElement('div');a.style.cssText='position:absolute;left:50%;top:-7px;width:2px;height:36px;transform:translateX(-50%);background:rgba(255,255,255,.85)';b.style.cssText='position:absolute;left:-7px;top:50%;width:36px;height:2px;transform:translateY(-50%);background:rgba(255,255,255,.85)';t.appendChild(a);t.appendChild(b);v.appendChild(t);return t}
function copy(src){let c=document.createElement('canvas');c.width=src.width;c.height=src.height;c.getContext('2d').drawImage(src,0,0);return c}
function density(stars,r){let r2=r*r,m=new Map;for(let i=0;i<stars.length;i++){let n=0,a=stars[i];for(let j=0;j<stars.length;j++){if(i===j)continue;let b=stars[j],dx=a.x-b.x,dy=a.y-b.y;if(dx*dx+dy*dy<r2)n++}m.set(a,n)}return m}
function score(s){let base=(s.score||0)+(s.peak||0)*2+(s.iso||0)*.22+(s.r||0)*.22;if(s.scale==='medium')base+=.5;if(s.scale==='large')base-=.6;if(S.bias==='bright')return base+(s.peak||0)*4;if(S.bias==='size')return base+(s.r||0)*1.8;if(S.bias==='isolated')return base+(s.iso||0)*1.8;return base}
function valid(s,d){let den=d.get(s)||0;if((s.structure||0)>.16)return false;if(den>15)return false;if(s.scale==='large'&&((s.iso||0)<1.5||den>9))return false;if((s.iso||0)<1.12||(s.compact||0)<.78)return false;return true}
function plan(stars){let want=Math.min(Number(($('move')&&$('move').value)||S.move||260),stars.length),d=density(stars,34),rank=stars.slice().sort((a,b)=>score(b)-score(a)),mov=[],spacing=Math.max(7,Math.min(S.src.width,S.src.height)/92);for(let s of rank){if(mov.length>=want)break;if(!valid(s,d))continue;let good=true;for(let t of mov)if(Math.hypot(s.x-t.x,s.y-t.y)<Math.max(spacing,(s.r+t.r)*.8)){good=false;break}if(good)mov.push(s)}for(let s of rank){if(mov.length>=want)break;if(valid(s,d)&&!mov.includes(s))mov.push(s)}let set=new Set(mov);return{moving:mov,staticStars:stars.filter(s=>!set.has(s)),density:d}}
function starLayer(src,stars){let W=src.width,H=src.height,c=document.createElement('canvas');c.width=W;c.height=H;let sd=src.getContext('2d').getImageData(0,0,W,H).data,ctx=c.getContext('2d'),id=ctx.createImageData(W,H),p=id.data;for(let s of stars){let r=Math.max(3,s.r*(s.scale==='large'?2.8:s.scale==='medium'?2.35:2));for(let y=Math.floor(s.y-r);y<=s.y+r;y++)for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||y<0||x>=W||y>=H)continue;let dist=Math.hypot(x-s.x,y-s.y);if(dist>r)continue;let a=1-cl(dist/r,0,1);a=a*a*(3-2*a);let k=(y*W+x)*4,lum=(.2126*sd[k]+.7152*sd[k+1]+.0722*sd[k+2])/255,al=cl(a*Math.max(0,lum-.025)*4.5,0,1);if(al*255>p[k+3]){p[k]=sd[k];p[k+1]=sd[k+1];p[k+2]=sd[k+2];p[k+3]=al*255|0}}}ctx.putImageData(id,0,0);return c}
function cleanBg(src,moving,dens){let W=src.width,H=src.height,c=copy(src),ctx=c.getContext('2d'),id=ctx.getImageData(0,0,W,H),p=id.data,o=new Uint8ClampedArray(p),removed=0;for(let s of moving){let den=dens.get(s)||0,small=s.scale==='small',med=s.scale==='medium',eligible=(s.structure||0)<.15&&den<12&&((small&&s.r<6.2)||(med&&s.r<5&&(s.iso||0)>1.45));if(!eligible)continue;let r=Math.max(2.3,Math.min(9.5,s.r*(small?1.65:1.42))),rin=r*1.24,rout=r*(small?3.1:3.35),samples=[];for(let yy=Math.floor(s.y-rout);yy<=s.y+rout;yy++)for(let xx=Math.floor(s.x-rout);xx<=s.x+rout;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;let d=Math.hypot(xx-s.x,yy-s.y);if(d<rin||d>rout)continue;let k=(yy*W+xx)*4,lum=.2126*o[k]+.7152*o[k+1]+.0722*o[k+2];samples.push([lum,o[k],o[k+1],o[k+2]])}if(samples.length<10)continue;samples.sort((a,b)=>a[0]-b[0]);let lo=Math.floor(samples.length*.12),hi=Math.ceil(samples.length*.7),rr=0,gg=0,bb=0,n=0;for(let i=lo;i<hi;i++){rr+=samples[i][1];gg+=samples[i][2];bb+=samples[i][3];n++}if(!n)continue;rr/=n;gg/=n;bb/=n;for(let yy=Math.floor(s.y-r);yy<=s.y+r;yy++)for(let xx=Math.floor(s.x-r);xx<=s.x+r;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;let d=Math.hypot(xx-s.x,yy-s.y);if(d>r)continue;let a=1-cl((d-r*.22)/(r*.78),0,1);a=a*a*(3-2*a)*(small?.82:.58);let k=(yy*W+xx)*4;p[k]=p[k]*(1-a)+rr*a;p[k+1]=p[k+1]*(1-a)+gg*a;p[k+2]=p[k+2]*(1-a)+bb*a}removed++}ctx.putImageData(id,0,0);c.dataset.removedStars=String(removed);return c}
function tier(s){let sc=(s.peak||0)*1.8+(s.r||0)*.45+(s.iso||0)*.12;if(sc>2.45||s.scale==='large')return 3;if(sc>1.55||s.scale==='medium')return 2;return 1}
function sprites(layer,stars){return stars.map(s=>{let pad=Math.ceil(Math.max(7,s.r*3)),x0=cl(Math.floor(s.x-pad),0,layer.width-1),y0=cl(Math.floor(s.y-pad),0,layer.height-1),x1=cl(Math.ceil(s.x+pad),0,layer.width),y1=cl(Math.ceil(s.y+pad),0,layer.height),w=Math.max(1,x1-x0),h=Math.max(1,y1-y0),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(layer,x0,y0,w,h,0,0,w,h);let ti=tier(s),depth=ti===3?1.65:ti===2?1.15:.82;return{...s,sp:c,ax:s.x-x0,ay:s.y-y0,w,h,tier:ti,depth}})}
function rect(img,w,h,t){let z=1+(S.zoom||0)*ez(t||0),ia=img.width/img.height,oa=w/h,bw,bh;if(ia>oa){bh=img.height;bw=bh*oa}else{bw=img.width;bh=bw/oa}let sw=bw/z,sh=bh/z,anx=S.anchorX==null?(S.cx==null?.5:S.cx):S.anchorX,any=S.anchorY==null?(S.cy==null?.5:S.cy):S.anchorY,ax=anx*img.width,ay=any*img.height;return{sx:cl(ax-sw/2,0,Math.max(0,img.width-sw)),sy:cl(ay-sh/2,0,Math.max(0,img.height-sh)),sw,sh}}
function map(x,y,r,w,h){return{x:(x-r.sx)/r.sw*w,y:(y-r.sy)/r.sh*h}}
function drawMov(ctx,w,h,r,t){let e=ez(t||0),ax=(S.anchorX==null?(S.cx||.5):S.anchorX)*S.src.width,ay=(S.anchorY==null?(S.cy||.5):S.anchorY)*S.src.height;for(let s of S.movers||[]){if(!s.sp)continue;let tm=s.tier===3?1.18:s.tier===2?1:.82,push=1+(S.fly||0)*.22*(s.depth||1)*tm*e,sx=ax+(s.x-ax)*push,sy=ay+(s.y-ay)*push,pt=map(sx,sy,r,w,h);if(pt.x<-120||pt.y<-120||pt.x>w+120||pt.y>h+120)continue;let sc=w/r.sw*(1+(S.grow||0)*.32*(s.depth||1)*tm*e);ctx.drawImage(s.sp,pt.x-s.ax*sc,pt.y-s.ay*sc,s.w*sc,s.h*sc)}}
function drawLayer(c,t){if(!ok()||!c)return;let ctx=c.getContext('2d'),w=c.width,h=c.height,mode=S.preview||'final';ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';if(mode==='mask'&&S.mask){let r=rect(S.mask.canvas,w,h,0);ctx.drawImage(S.mask.canvas,r.sx,r.sy,r.sw,r.sh,0,0,w,h);return}if(mode==='moving'){let r=rect(S.src,w,h,0);drawMov(ctx,w,h,r,0);return}if(mode==='stars'&&S.staticLayer){let r=rect(S.staticLayer,w,h,0);ctx.drawImage(S.staticLayer,r.sx,r.sy,r.sw,r.sh,0,0,w,h);return}if(mode==='starless'&&S.backgroundLayer){let r=rect(S.backgroundLayer,w,h,0);ctx.drawImage(S.backgroundLayer,r.sx,r.sy,r.sw,r.sh,0,0,w,h);return}let bg=S.backgroundLayer||S.starless||S.src,r=rect(bg,w,h,mode==='final'?t:0);ctx.drawImage(bg,r.sx,r.sy,r.sw,r.sh,0,0,w,h);if(mode==='final')drawMov(ctx,w,h,r,t||0)}
function target(){if(!ok())return;let tg=marker(),c=$('main'),v=document.querySelector('.view');if(!tg||!c||!v)return;if((S.preview||'final')!=='final'){tg.style.display='none';return}let img=S.backgroundLayer||S.src,r=rect(img,c.width,c.height,S.last||0),px=(S.anchorX==null?(S.cx||.5):S.anchorX)*img.width,py=(S.anchorY==null?(S.cy||.5):S.anchorY)*img.height,pt=map(px,py,r,c.width,c.height),cr=c.getBoundingClientRect(),vr=v.getBoundingClientRect();tg.style.left=cr.left-vr.left+pt.x+'px';tg.style.top=cr.top-vr.top+pt.y+'px';tg.style.display='block'}
function renderLayer(t){if(!ok())return;try{if(typeof size==='function')size(S.src.width,S.src.height)}catch(e){}drawLayer($('main'),t||0);S.last=t||0;target()}
function anchor(ev){if(!ok())return;let c=$('main'),cr=c.getBoundingClientRect(),x=(ev.clientX-cr.left)/cr.width,y=(ev.clientY-cr.top)/cr.height;if(x<0||x>1||y<0||y>1)return;let img=S.backgroundLayer||S.src,r=rect(img,c.width,c.height,S.last||0);S.anchorX=cl((r.sx+x*r.sw)/img.width,.02,.98);S.anchorY=cl((r.sy+y*r.sh)/img.height,.02,.98);S.cx=S.anchorX;S.cy=S.anchorY;st('Zoom target locked');ev.stopImmediatePropagation&&ev.stopImmediatePropagation();ev.preventDefault&&ev.preventDefault();renderLayer(S.last||0)}
async function build070(){if(!ok())return;stop();let btn=$('build');if(btn)btn.disabled=true;prog('Analyzing stars',10,'v0.7.0: building layered motion engine…');await sleep(20);let prev=window.__dsd_prev_build;if(typeof prev==='function')await prev();if(!S.stars||!S.stars.length){hide();if(btn)btn.disabled=false;st('No stars detected');return}prog('Separating layers',35,'Selecting moving and static stars…');await sleep(20);let pl=plan(S.stars);prog('Separating layers',58,'Removing moving stars from the background…');await sleep(20);S.backgroundLayer=cleanBg(S.src,pl.moving,pl.density);prog('Separating layers',75,'Building static star layer…');await sleep(20);S.staticLayer=starLayer(S.src,pl.staticStars);prog('Separating layers',88,'Building moving stars and parallax tiers…');await sleep(20);S.movingLayer=starLayer(S.src,pl.moving);S.movers=sprites(S.movingLayer,pl.moving);S.movingCatalog=pl.moving;S.staticCatalog=pl.staticStars;S.starless=S.backgroundLayer;S.starsOnly=S.staticLayer;S.move=S.movers.length;S.statics=[];if(S.anchorX==null||S.anchorY==null){let top=pl.moving.slice(0,Math.min(25,pl.moving.length));if(top.length){S.anchorX=cl(top.reduce((a,b)=>a+b.x,0)/top.length/S.src.width,.04,.96);S.anchorY=cl(top.reduce((a,b)=>a+b.y,0)/top.length/S.src.height,.04,.96);S.cx=S.anchorX;S.cy=S.anchorY}}if($('mv'))$('mv').textContent=String(S.movers.length);if($('stats')){$('stats').style.display='block';$('stats').textContent=`${(S.stars||[]).length} candidates · ${(S.backgroundLayer.dataset.removedStars||'0')} moving stars removed from background · ${S.movers.length} moving`}ver();labels();hide();if(btn){btn.disabled=false;btn.textContent='Create Motion'}if($('play'))$('play').disabled=false;if($('export'))$('export').disabled=false;renderLayer(0);st('v0.7.0 layered motion ready')}
function install(){window.__dsd_prev_build=window.__dsd_prev_build||(typeof build==='function'?build:null);ver();labels();marker();try{build=build070;draw=drawLayer;render=renderLayer;target=target}catch(e){}let c=$('main');if(c&&!c.dataset.v070){c.dataset.v070=1;c.addEventListener('pointerdown',anchor,true)}window.addEventListener('resize',()=>{try{renderLayer(S.last||0)}catch(e){}});let p=$('preview');if(p&&!p.dataset.v070){p.dataset.v070=1;p.addEventListener('change',()=>setTimeout(()=>renderLayer(S.last||0),0))}let btn=$('build');if(btn&&!btn.dataset.v070){let clone=btn.cloneNode(true);clone.dataset.v070=1;btn.parentNode.replaceChild(clone,btn);clone.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation&&e.stopImmediatePropagation();build070()},true)}}
document.addEventListener('DOMContentLoaded',install);
})();