(function(){
  const VERSION='v0.6.6';
  const $=id=>document.getElementById(id);
  const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function hasState(){try{return typeof S!=='undefined'&&S&&S.src}catch(e){return false}}
  function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}
  function stopPreview(){try{S.play=0;cancelAnimationFrame(S.raf)}catch(e){} const b=$('play'); if(b)b.textContent='▶ Play'}
  function setStatus(x){const s=$('status');if(s)s.textContent=x}
  function setVersion(){const v=document.querySelector('.ver');if(v)v.textContent=VERSION;const b=$('badge');if(b)b.textContent=VERSION+' · conservative starless'}
  function prog(t,p,l){const o=$('ol');if(o)o.style.display='grid';if($('olt'))$('olt').textContent=t;if($('fill'))$('fill').style.width=clamp(p,0,100)+'%';if($('oll'))$('oll').textContent=l||'';setStatus(l||t)}
  function hide(){const o=$('ol');if(o)o.style.display='none'}
  function ios(){const u=navigator.userAgent||'',i=/iPad/.test(u)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),p=/iPhone|iPod/.test(u);return(i||p)&&/WebKit/.test(u)&&!/CriOS|FxiOS/.test(u)}
  function rawDims(){const v=$('preset')&&$('preset').value;return v==='landscape'?{w:1920,h:1080,l:'16x9'}:v==='square'?{w:1080,h:1080,l:'1x1'}:{w:1080,h:1920,l:'9x16'}}
  function perfDims(d){if(!ios())return d;if(d.w===1920)return{w:1280,h:720,l:d.l};if(d.h===1920)return{w:720,h:1280,l:d.l};return{w:900,h:900,l:d.l}}
  function patchDims(){try{if(typeof dims==='function'&&!window.__dsd_dims_066){const old=dims;dims=function(){return perfDims(old())};window.__dsd_dims_066=1}}catch(e){}}
  function exportNote(){const e=$('exinfo');if(!e)return;const r=rawDims(),d=perfDims(r),n=(r.w!==d.w||r.h!==d.h)?` · performance export ${d.w}×${d.h} on iPad/Safari`:'';e.textContent=`Export target: ${r.w}×${r.h} at 30 fps${n}`}
  function copyCanvas(src){const c=document.createElement('canvas');c.width=src.width;c.height=src.height;c.getContext('2d').drawImage(src,0,0);return c}
  function blur(src,W,H,r){const tmp=new Float32Array(W*H),out=new Float32Array(W*H),ww=2*r+1;for(let y=0;y<H;y++){let s=0;for(let x=-r;x<=r;x++)s+=src[y*W+clamp(x,0,W-1)];for(let x=0;x<W;x++){tmp[y*W+x]=s/ww;s+=src[y*W+clamp(x+r+1,0,W-1)]-src[y*W+clamp(x-r,0,W-1)]}}for(let x=0;x<W;x++){let s=0;for(let y=-r;y<=r;y++)s+=tmp[clamp(y,0,H-1)*W+x];for(let y=0;y<H;y++){out[y*W+x]=s/ww;s+=tmp[clamp(y+r+1,0,H-1)*W+x]-tmp[clamp(y-r,0,H-1)*W+x]}}return out}
  function med(arr){const smp=[],step=Math.max(1,Math.floor(arr.length/4000));for(let i=0;i<arr.length;i+=step)smp.push(arr[i]);smp.sort((a,b)=>a-b);return smp[Math.floor(smp.length/2)]||0}
  function mad(arr,m){const smp=[],step=Math.max(1,Math.floor(arr.length/4000));for(let i=0;i<arr.length;i+=step)smp.push(Math.abs(arr[i]-m));smp.sort((a,b)=>a-b);return(smp[Math.floor(smp.length/2)]||0)*1.4826+1e-6}
  function connected(score,W,H,th,scale,scaleR,L,bg,structure){const visit=new Uint8Array(W*H),dirs=[1,-1,W,-W,W+1,W-1,-W+1,-W-1],out=[];for(let i=0;i<W*H;i++){if(visit[i]||score[i]<th)continue;const q=[i],pts=[];visit[i]=1;while(q.length){const p0=q.pop();pts.push(p0);const x=p0%W,y=p0/W|0;for(const d of dirs){const n=p0+d,nx=n%W,ny=n/W|0;if(n<0||n>=W*H||visit[n]||Math.abs(nx-x)>1||Math.abs(ny-y)>1)continue;if(score[n]>th*.48){visit[n]=1;q.push(n)}}}const area=pts.length;if(area<1||area>260)continue;let sx=0,sy=0,flux=0,peak=0,minx=W,maxx=0,miny=H,maxy=0,stsum=0;for(const p0 of pts){const x=p0%W,y=p0/W|0,v=Math.max(0,L[p0]-bg[p0]);sx+=x*v;sy+=y*v;flux+=v;peak=Math.max(peak,score[p0]);minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);stsum+=structure[p0]}if(flux<=0)continue;const cx=sx/flux,cy=sy/flux,bw=maxx-minx+1,bh=maxy-miny+1,aspect=Math.max(bw,bh)/Math.max(1,Math.min(bw,bh)),rad=Math.sqrt(area/Math.PI),str=stsum/area;if(aspect>2.45||rad>8.2)continue;let ring=0,rn=0,r1=Math.max(3,rad*1.8),r2=Math.max(5,rad*4.2);for(let yy=Math.floor(cy-r2);yy<=cy+r2;yy++)for(let xx=Math.floor(cx-r2);xx<=cx+r2;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const dd=Math.hypot(xx-cx,yy-cy);if(dd>r1&&dd<r2){ring+=Math.max(0,L[yy*W+xx]-bg[yy*W+xx]);rn++}}const ann=ring/Math.max(1,rn),iso=peak/Math.max(1e-6,ann+.001),compact=peak/Math.max(1e-6,flux/Math.max(1,area));if(iso<1.15||compact<.75)continue;if(str>.16&&(iso<2.2||compact<1.35||peak<th*1.35))continue;const sv=peak*2.1+Math.sqrt(flux)*.75+iso*.28+compact*.4-rad*.04-str*1.2;out.push({x:cx*2,y:cy*2,r:Math.max(1.15,rad*2*scaleR),peak,flux,iso,compact,structure:str,scale,score:sv})}return out}
  function detectCandidates(src){const W=Math.max(80,src.width/2|0),H=Math.max(80,src.height/2|0),c=document.createElement('canvas');c.width=W;c.height=H;c.getContext('2d').drawImage(src,0,0,W,H);const p=c.getContext('2d').getImageData(0,0,W,H).data,L=new Float32Array(W*H);for(let i=0;i<W*H;i++)L[i]=(.2126*p[i*4]+.7152*p[i*4+1]+.0722*p[i*4+2])/255;const bg=blur(L,W,H,22),b1=blur(L,W,H,1),b2=blur(L,W,H,2),b4=blur(L,W,H,4),b8=blur(L,W,H,8),b16=blur(L,W,H,16),structure=new Float32Array(W*H),hf1=new Float32Array(W*H),hf2=new Float32Array(W*H),hf3=new Float32Array(W*H);for(let i=0;i<L.length;i++){structure[i]=Math.max(0,b8[i]-b16[i]);hf1[i]=Math.max(0,b1[i]-b2[i]);hf2[i]=Math.max(0,b2[i]-b4[i]);hf3[i]=Math.max(0,b4[i]-b8[i])}const m1=med(hf1),m2=med(hf2),m3=med(hf3),n1=mad(hf1,m1),n2=mad(hf2,m2),n3=mad(hf3,m3),strict=clamp(S.strict||.7,.3,.95);let stars=[];stars=stars.concat(connected(hf1,W,H,m1+n1*(1.7+strict*2.3),'small',.9,L,bg,structure));stars=stars.concat(connected(hf2,W,H,m2+n2*(1.55+strict*2.05),'medium',1.1,L,bg,structure));stars=stars.concat(connected(hf3,W,H,m3+n3*(1.85+strict*2.6),'large',1.35,L,bg,structure));stars.sort((a,b)=>b.score-a.score);const ded=[];for(const s of stars){let dup=false;for(const d of ded){if(Math.hypot(s.x-d.x,s.y-d.y)<Math.max(3.5,(s.r+d.r)*.65)){dup=true;if(s.score>d.score)Object.assign(d,s);break}}if(!dup)ded.push(s);if(ded.length>Math.max(300,(S.max||2200)*1.25))break}return ded.slice(0,Math.max(100,Math.min(S.max||2200,ded.length)))}
  function diagnosticMask(src,stars){const W=src.width,H=src.height,a=new Float32Array(W*H);for(const s of stars){const protect=clamp(s.structure||0,0,.35),halo=s.scale==='large'?2.35:s.scale==='medium'?1.9:1.55,r=Math.max(2.5,s.r*halo*(1-protect*.9)),core=Math.max(1.3,r*.42);for(let y=Math.floor(s.y-r);y<=s.y+r;y++)for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||y<0||x>=W||y>=H)continue;const d=Math.hypot(x-s.x,y-s.y);if(d>r)continue;let v=d<core?1:1-clamp((d-core)/(r-core),0,1);v=v*v*(3-2*v);const k=y*W+x;if(v>a[k])a[k]=v}}const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d'),id=ctx.createImageData(W,H),p=id.data;for(let i=0;i<a.length;i++){const v=a[i]*255|0,k=i*4;p[k]=p[k+1]=p[k+2]=v;p[k+3]=255}ctx.putImageData(id,0,0);return{a,canvas:c}}
  function conservativeStarless(src,stars){const W=src.width,H=src.height,c=copyCanvas(src),ctx=c.getContext('2d'),id=ctx.getImageData(0,0,W,H),p=id.data,orig=new Uint8ClampedArray(p);let removed=0;for(const s of stars){const eligible=s.scale==='small'&&s.r<4.2&&(s.structure||0)<.09&&(s.iso||0)>1.45&&(s.compact||0)>1.0;if(!eligible)continue;const r=Math.max(2.2,Math.min(7.5,s.r*1.35)),rIn=r*1.35,rOut=r*2.8,samp=[];for(let yy=Math.floor(s.y-rOut);yy<=s.y+rOut;yy++)for(let xx=Math.floor(s.x-rOut);xx<=s.x+rOut;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const d=Math.hypot(xx-s.x,yy-s.y);if(d<rIn||d>rOut)continue;const k=(yy*W+xx)*4,lum=.2126*orig[k]+.7152*orig[k+1]+.0722*orig[k+2];samp.push([lum,orig[k],orig[k+1],orig[k+2]])}if(samp.length<8)continue;samp.sort((a,b)=>a[0]-b[0]);const lo=Math.floor(samp.length*.15),hi=Math.ceil(samp.length*.75);let rr=0,gg=0,bb=0,n=0;for(let i=lo;i<hi;i++){rr+=samp[i][1];gg+=samp[i][2];bb+=samp[i][3];n++}if(!n)continue;rr/=n;gg/=n;bb/=n;for(let yy=Math.floor(s.y-r);yy<=s.y+r;yy++)for(let xx=Math.floor(s.x-r);xx<=s.x+r;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const d=Math.hypot(xx-s.x,yy-s.y);if(d>r)continue;let a=1-clamp((d-r*.28)/(r*.72),0,1);a=a*a*(3-2*a)*.72;const k=(yy*W+xx)*4;p[k]=p[k]*(1-a)+rr*a;p[k+1]=p[k+1]*(1-a)+gg*a;p[k+2]=p[k+2]*(1-a)+bb*a}removed++}ctx.putImageData(id,0,0);c.dataset.removedStars=String(removed);return c}
  function transparentStarsLayer(src,stars){const W=src.width,H=src.height,c=document.createElement('canvas');c.width=W;c.height=H;const srcData=src.getContext('2d').getImageData(0,0,W,H).data,ctx=c.getContext('2d'),id=ctx.createImageData(W,H),p=id.data;for(const s of stars){const r=Math.max(3,s.r*(s.scale==='large'?2.8:s.scale==='medium'?2.35:2));for(let y=Math.floor(s.y-r);y<=s.y+r;y++)for(let x=Math.floor(s.x-r);x<=s.x+r;x++){if(x<0||y<0||x>=W||y>=H)continue;const d=Math.hypot(x-s.x,y-s.y);if(d>r)continue;let a=1-clamp(d/r,0,1);a=a*a*(3-2*a);const k=(y*W+x)*4,lum=(.2126*srcData[k]+.7152*srcData[k+1]+.0722*srcData[k+2])/255,alpha=clamp(a*Math.max(0,lum-.025)*4.5,0,1);if(alpha*255>p[k+3]){p[k]=srcData[k];p[k+1]=srcData[k+1];p[k+2]=srcData[k+2];p[k+3]=alpha*255|0}}}ctx.putImageData(id,0,0);return c}
  function scoreStar(s){let base=(s.score||0)+(s.peak||0)*2+(s.iso||0)*.18+(s.r||0)*.25;if(S.bias==='bright')return base+(s.peak||0)*4;if(S.bias==='size')return base+(s.r||0)*1.8;if(S.bias==='isolated')return base+(s.iso||0)*1.5;return base}
  function chooseMoving(stars){const desired=Math.min(Number(($('move')&&$('move').value)||S.move||260),stars.length),ranked=stars.slice().sort((a,b)=>scoreStar(b)-scoreStar(a)),chosen=[],spacing=Math.max(6,Math.min(S.src.width,S.src.height)/85);for(const s of ranked){if(chosen.length>=desired)break;let ok=true;for(const t of chosen){if(Math.hypot(s.x-t.x,s.y-t.y)<Math.max(spacing,(s.r+t.r)*.8)){ok=false;break}}if(ok)chosen.push(s)}for(const s of ranked){if(chosen.length>=desired)break;if(!chosen.includes(s))chosen.push(s)}return chosen}
  function makeSprite(layer,s){const pad=Math.ceil(Math.max(7,s.r*3)),x0=clamp(Math.floor(s.x-pad),0,layer.width-1),y0=clamp(Math.floor(s.y-pad),0,layer.height-1),x1=clamp(Math.ceil(s.x+pad),0,layer.width),y1=clamp(Math.ceil(s.y+pad),0,layer.height),w=Math.max(1,x1-x0),h=Math.max(1,y1-y0),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(layer,x0,y0,w,h,0,0,w,h);return{...s,sp:c,ax:s.x-x0,ay:s.y-y0,w,h,depth:clamp(.75+(s.peak||0)*2+(s.r||0)*.05,.75,1.8)}}
  async function buildSafe(){if(!hasState())return;stopPreview();const btn=$('build');if(btn)btn.disabled=true;prog('Analyzing stars',5,'v0.6.6: detecting protected star mask…');await sleep(20);const stars=detectCandidates(S.src);prog('Analyzing stars',35,'Building improved soft mask…');await sleep(20);S.stars=stars;S.mask=diagnosticMask(S.src,stars);prog('Creating starless',55,'Conservatively removing small isolated stars…');await sleep(20);S.starless=conservativeStarless(S.src,stars);prog('Creating layers',75,'Creating alpha-correct stars layer…');await sleep(20);S.starsOnly=transparentStarsLayer(S.src,stars);const moving=chooseMoving(stars);S.movers=moving.map(s=>makeSprite(S.starsOnly,s));S.statics=[];S.map=1;S.move=S.movers.length;const removed=S.starless.dataset.removedStars||'0';if($('mv'))$('mv').textContent=String(S.movers.length);if($('stats')){$('stats').style.display='block';$('stats').textContent=`${stars.length} candidates · ${removed} small stars softened · ${S.movers.length} moving`}prog('Ready',100,'Conservative starless ready');await sleep(20);hide();if(btn){btn.disabled=false;btn.textContent='Recreate Motion'}if($('play'))$('play').disabled=false;if($('export'))$('export').disabled=false;setVersion();render(0);setStatus('v0.6.6 conservative starless ready')}
  function sourceRect(img,w,h,t){const z=1+(S.zoom||0)*ease(t||0),ia=img.width/img.height,oa=w/h;let bw,bh;if(ia>oa){bh=img.height;bw=bh*oa}else{bw=img.width;bh=bw/oa}const sw=bw/z,sh=bh/z,ax=(S.cx==null?.5:S.cx)*img.width,ay=(S.cy==null?.5:S.cy)*img.height;return{sx:clamp(ax-sw/2,0,Math.max(0,img.width-sw)),sy:clamp(ay-sh/2,0,Math.max(0,img.height-sh)),sw,sh}}
  function mapxy(x,y,r,w,h){return{x:(x-r.sx)/r.sw*w,y:(y-r.sy)/r.sh*h}}
  function drawStars(ctx,w,h,r,t){const e=ease(t||0),ax=(S.cx||.5)*S.src.width,ay=(S.cy||.5)*S.src.height;for(const s of S.movers||[]){if(!s.sp)continue;const push=1+(S.fly||0)*.24*(s.depth||1)*e,sx=ax+(s.x-ax)*push,sy=ay+(s.y-ay)*push,p=mapxy(sx,sy,r,w,h);if(p.x<-120||p.y<-120||p.x>w+120||p.y>h+120)continue;const sc=w/r.sw*(1+(S.grow||0)*.35*(s.depth||1)*e);ctx.drawImage(s.sp,p.x-s.ax*sc,p.y-s.ay*sc,s.w*sc,s.h*sc)}}
  function tunedDraw(c,t){if(!hasState()||!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height,mode=S.preview||'final';ctx.clearRect(0,0,w,h);let img=mode==='mask'&&S.mask?S.mask.canvas:mode==='stars'&&S.starsOnly?S.starsOnly:mode==='moving'?null:S.starless||S.src;if(mode==='moving'){drawStars(ctx,w,h,sourceRect(S.src,w,h,0),0);return}const r=sourceRect(img,w,h,mode==='final'?t:0);ctx.drawImage(img,r.sx,r.sy,r.sw,r.sh,0,0,w,h);if(mode==='final')drawStars(ctx,w,h,r,t||0)}
  function tunedRender(t){if(!hasState())return;try{if(typeof size==='function')size(S.src.width,S.src.height)}catch(e){}tunedDraw($('main'),t||0);S.last=t||0;try{if(typeof target==='function')target()}catch(e){}}
  function install(){try{build=buildSafe;draw=tunedDraw;render=tunedRender}catch(e){}patchDims();exportNote();setVersion()}
  function hooks(){const btn=$('build'),preset=$('preset'),exp=$('export');if(btn&&!btn.dataset.v066){btn.dataset.v066=1;btn.addEventListener('click',e=>{e.stopImmediatePropagation&&e.stopImmediatePropagation();e.preventDefault&&e.preventDefault();buildSafe()},true)}if(preset&&!preset.dataset.v066){preset.dataset.v066=1;preset.addEventListener('change',exportNote)}if(exp&&!exp.dataset.v066){exp.dataset.v066=1;exp.addEventListener('click',()=>{stopPreview();S.statics=[];patchDims();exportNote()},true)}}
  document.addEventListener('DOMContentLoaded',()=>{install();hooks()});
})();
