(function(){
  if(document.getElementById('deepskydrift-schema')) return;
  const graph={"@context":"https://schema.org","@graph":[
    {"@type":"Organization","@id":"https://dwarfastro.com/#organization","name":"DwarfAstro","url":"https://dwarfastro.com/"},
    {"@type":"WebSite","@id":"https://deepskydrift.dwarfastro.com/#website","name":"DeepSkyDrift","url":"https://deepskydrift.dwarfastro.com/","publisher":{"@id":"https://dwarfastro.com/#organization"}},
    {"@type":"WebPage","@id":"https://deepskydrift.dwarfastro.com/#webpage","url":"https://deepskydrift.dwarfastro.com/","name":"DeepSkyDrift | Create Motion Videos from Astrophotography Images","description":"Create subtle cinematic motion videos from your astrophotography images. DeepSkyDrift runs locally in your browser, keeps your images on your device, and exports videos for Reels, Shorts, and social sharing.","isPartOf":{"@id":"https://deepskydrift.dwarfastro.com/#website"},"about":{"@id":"https://deepskydrift.dwarfastro.com/#software"},"publisher":{"@id":"https://dwarfastro.com/#organization"},"breadcrumb":{"@id":"https://deepskydrift.dwarfastro.com/#breadcrumb"}},
    {"@type":"SoftwareApplication","@id":"https://deepskydrift.dwarfastro.com/#software","name":"DeepSkyDrift","url":"https://deepskydrift.dwarfastro.com/","applicationCategory":"MultimediaApplication","applicationSubCategory":"Astrophotography video tool","operatingSystem":"Web browser","browserRequirements":"Requires a modern browser with canvas and media recording support.","description":"DeepSkyDrift is a free browser-based tool that turns finished astrophotography images into subtle cinematic motion videos. Images are processed locally in the browser and are not uploaded to a server.","creator":{"@id":"https://dwarfastro.com/#organization"},"publisher":{"@id":"https://dwarfastro.com/#organization"},"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"featureList":["Create motion videos from astrophotography images","Choose Gentle, Cinematic, or Deep Fly-In motion styles","Set the zoom center by tapping or clicking the image","Export portrait, wide, or square videos","Runs locally in the browser without uploading images"]},
    {"@type":"HowTo","@id":"https://deepskydrift.dwarfastro.com/#howto","name":"How to create an astrophotography motion video with DeepSkyDrift","description":"Use DeepSkyDrift to create a subtle motion video from a finished astrophotography image.","step":[{"@type":"HowToStep","name":"Load your image","text":"Choose a finished JPG, PNG, or WebP astrophotography image."},{"@type":"HowToStep","name":"Create motion","text":"Let DeepSkyDrift analyze the image and create a stars-only motion layer."},{"@type":"HowToStep","name":"Choose a motion style","text":"Select Gentle, Cinematic, or Deep Fly-In."},{"@type":"HowToStep","name":"Set the zoom center","text":"Tap or click the galaxy, nebula, or subject you want the motion to move toward."},{"@type":"HowToStep","name":"Export your video","text":"Choose Portrait, Wide, or Square format and export the finished video."}]},
    {"@type":"FAQPage","@id":"https://deepskydrift.dwarfastro.com/#faq","mainEntity":[{"@type":"Question","name":"Does DeepSkyDrift upload my image?","acceptedAnswer":{"@type":"Answer","text":"No. DeepSkyDrift processes your image locally in your browser. Your image is not uploaded to DwarfAstro or any server."}},{"@type":"Question","name":"What image formats work with DeepSkyDrift?","acceptedAnswer":{"@type":"Answer","text":"DeepSkyDrift is intended for finished JPG, PNG, or WebP astrophotography images."}},{"@type":"Question","name":"Can I use DWARF 3 images with DeepSkyDrift?","acceptedAnswer":{"@type":"Answer","text":"Yes. DeepSkyDrift works with finished DWARF 3 images as well as images from other smart telescopes or traditional astrophotography workflows."}},{"@type":"Question","name":"Is DeepSkyDrift real 3D motion?","acceptedAnswer":{"@type":"Answer","text":"No. DeepSkyDrift creates a 2D motion effect from a still image. It is designed to make a finished astrophotography image feel more cinematic for sharing."}},{"@type":"Question","name":"Why is my iPad export not full HD?","acceptedAnswer":{"@type":"Answer","text":"Some iPad and Safari combinations downscale canvas video recording even when a higher export size is requested. Desktop Chrome or Edge is recommended when full-resolution export is important."}},{"@type":"Question","name":"Is DeepSkyDrift free?","acceptedAnswer":{"@type":"Answer","text":"Yes. DeepSkyDrift is free to use."}}]},
    {"@type":"BreadcrumbList","@id":"https://deepskydrift.dwarfastro.com/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"DwarfAstro","item":"https://dwarfastro.com/"},{"@type":"ListItem","position":2,"name":"DeepSkyDrift","item":"https://deepskydrift.dwarfastro.com/"}]}
  ]};
  const s=document.createElement('script');
  s.id='deepskydrift-schema';
  s.type='application/ld+json';
  s.textContent=JSON.stringify(graph);
  document.head.appendChild(s);
})();
