/* DeepSkyDrift star-engine.js — classical background-aware star extraction for v0.9.1 */
(function(){
const V='v0.9.1-star-engine';let cache=null;const $=id=>document.getElementById(id),cl=(v,a,b)=>v<a?a:v>b?b:v,ci=(v,a,b)=>cl(v|0,a,b),tick=()=>new Promise(r=>requestAnimationFrame(r));
function say(s){try{st(s)}catch(e){}}function prog2(t,p,l){try{prog(t,p,l||t)}catch(e){say(l||t)}}function end(){try{hide()}catch(e){}}function r(){try{installRenderOverride&&installRenderOverride()}catch(e){}try{render088?render088(S.last||0):render(S.last||0)}catch(e){}}
function med(a){a=Array.from(a);if(!a.length)return 0;a.sort((x,y)=>x-y);let m=a.length>>1;return a.length&1?a[m]:(a[m-1]+a[m])*.5}
function canvasData(c){let w=c.width,h=c.height,img=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h),d=img.data,n=w*h,L=new Float32Array(n),R=new Float32Array(n),G=new Float32Array(n),B=new Float32Array(n);for(let i=0,p=0;i<n;i++,p+=4){R[i]=d[p];G[i]=d[p+1];B[i]=d[p+2];L[i]=.2126*d[p]+.7152*d[p+1]+.0722*d[p+2]}return{w,h,img,L,ch:[R,G,B]}}
function toCanvas(ch,w,h){let c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d'),im=x.createImageData(w,h),d=im.data,n=w*h;for(let i=0,p=0;i<n;i++,p+=4){d[p]=cl(ch[0][i]|0,0,255);d[p+1]=cl(ch[1][i]|0,0,255);d[p+2]=cl(ch[2][i]|0,0,255);d[p+3]=255}x.putImageData(im,0,0);return c}
function maskCanvas(m,w,h){let c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d'),im=x.createImageData(w,h),d=im.data;for(let i=0,p=0;i<m.length;i++,p+=4){let v=m[i]?255:0;d[p]=d[p+1]=d[p+2]=v;d[p+3]=255}x.putImageData(im,0,0);return c}
function background(a,w,h,f=16){let cw=Math.ceil(w/f),ch=Math.ceil(h/f),co=new Float32Array(cw*ch),buf=[];for(let by=0;by<ch;by++)for(let bx=0;bx<cw;bx++){buf.length=0;for(let y=by*f;y<Math.min(h,by*f+f);y++)for(let x=bx*f;x<Math.min(w,bx*f+f);x++)buf.push(a[y*w+x]);co[by*cw+bx]=med(buf)}let o=new Float32Array(w*h);for(let y=0;y<h;y++){let gy=cl((y+.5)*ch/h-.5,0,ch-1),y0=gy|0,y1=Math.min(ch-1,y0+1),fy=gy-y0;for(let x=0;x<w;x++){let gx=cl((x+.5)*cw/w-.5,0,cw-1),x0=gx|0,x1=Math.min(cw-1,x0+1),fx=gx-x0,a0=co[y0*cw+x0]*(1-fx)+co[y0*cw+x1]*fx,a1=co[y1*cw+x0]*(1-fx)+co[y1*cw+x1]*fx;o[y*w+x]=a0*(1-fy)+a1*fy}}return o}
function noise(a){let s=[],step=Math.max(4,Math.floor(a.length/160000));for(let i=0;i<a.length;i+=step)s.push(a[i]);let m=med(s);for(let i=0;i<s.length;i++)s[i]=Math.abs(s[i]-m);return Math.max(.001,1.4826*med(s))}
function detect(res,w,h,n){let thr=(2.35+cl(S.strict||.7,.3,.95)*3.25)*n,stars=[],used=new Uint8Array(w*h),maxR=Math.max(12,Math.min(26,10+(S.rad||2.5)*4));for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){let i=y*w+x,v=res[i];if(v<thr||used[i])continue;if(v<res[i-1]||v<res[i+1]||v<res[i-w]||v<res[i+w]||v<res[i-w-1]||v<res[i+w+1])continue;let grow=Math.max(n,v*.10),q=[i],minx=x,maxx=x,miny=y,maxy=y,sx=0,sy=0,sw=0,area=0,bad=false;while(q.length){let p=q.pop();if(used[p]||res[p]<grow)continue;used[p]=1;area++;let px=p%w,py=(p/w)|0,wt=res[p];sx+=px*wt;sy+=py*wt;sw+=wt;if(px<minx)minx=px;if(px>maxx)maxx=px;if(py<miny)miny=py;if(py>maxy)maxy=py;if(area>Math.PI*maxR*maxR*1.6){bad=true;break}if(px>0)q.push(p-1);if(px<w-1)q.push(p+1);if(py>0)q.push(p-w);if(py<h-1)q.push(p+w)}let rad=Math.max((maxx-minx+1)/2,(maxy-miny+1)/2),elong=Math.max(maxx-minx+1,maxy-miny+1)/Math.max(1,Math.min(maxx-minx+1,maxy-miny+1));if(!bad&&area>=2&&rad<=maxR&&elong<4.2)stars.push({x:sx/sw,y:sy/sw,radius:rad,peak:v,snr:v/n})}stars.sort((a,b)=>b.peak-a.peak);let out=[];for(let s of stars){let dup=false;for(let j=Math.max(0,out.length-2500);j<out.length;j++){let o=out[j],dx=s.x-o.x,dy=s.y-o.y,R=Math.max(2.5,s.radius*1.45,o.radius*1.45);if(dx*dx+dy*dy<R*R){dup=true;break}}if(!dup)out.push(s)}return out}
function margin(s){return(s.radius+1.1+1.65*Math.log10(Math.max(1,s.snr)))*(S.rad||2.5)/2.5}
function mkMask(stars,w,h){let m=new Uint8Array(w*h);for(let s of stars){let r=s.maskRadius||margin(s);for(let y=ci(s.y-r,0,h-1);y<=ci(s.y+r,0,h-1);y++)for(let x=ci(s.x-r,0,w-1);x<=ci(s.x+r,0,w-1);x++){let dx=x-s.x,dy=y-s.y;if(dx*dx+dy*dy<=r*r)m[y*w+x]=1}}return m}
function fill(ch,mask,bgs,w,h){let out=ch.map(c=>c.slice()),idx=[];for(let i=0;i<mask.length;i++)if(mask[i]){idx.push(i);for(let c=0;c<3;c++)out[c][i]=bgs[c][i]}for(let it=0;it<120;it++)for(let p of idx){let x=p%w,y=(p/w)|0;for(let c=0;c<3;c++)out[c][p]=((x?out[c][p-1]:out[c][p])+(x<w-1?out[c][p+1]:out[c][p])+(y?out[c][p-w]:out[c][p])+(y<h-1?out[c][p+w]:out[c][p]))*.25}return out}
function classify(stars,img,w,h){let all=stars.slice(0,Math.max(50,S.max||2200));for(let i=0;i<all.length;i++){let s=all[i];s._id=i+1;s.maskRadius=cl(margin(s),2,36);s.spriteRadius=cl(s.maskRadius+3,5,44);let hot=0,tot=0,d=img.data,r=s.maskRadius;for(let y=ci(s.y-r,0,h-1);y<=ci(s.y+r,0,h-1);y++)for(let x=ci(s.x-r,0,w-1);x<=ci(s.x+r,0,w-1);x++){let p=(y*w+x)*4;if(d[p]>247||d[p+1]>247||d[p+2]>247)hot++;tot++}s.haloRisk=s.radius>7.5||s.maskRadius>15||s.snr>90||(tot&&hot/tot>.025)}function score(s){let b=S.bias||'balanced';return b==='bright'?s.snr:b==='size'?s.radius*40+s.snr*.25:b==='isolated'?(s.haloRisk?0:80)+s.snr*.2:s.snr*.45+s.radius*22+(s.haloRisk?-80:20)}let ranked=all.slice().sort((a,b)=>score(b)-score(a)),target=Math.min(S.move||260,ranked.length),movers=ranked.filter(s=>!s.haloRisk).slice(0,target);if(movers.length<Math.min(target,80))movers=movers.concat(ranked.filter(s=>s.haloRisk).slice(0,target-movers.length));movers.forEach((s,i)=>s.tier=i<movers.length*.16?3:i<movers.length*.46?2:1);let ids=new Set(movers.map(s=>s._id));return{all,movers,statics:all.filter(s=>!ids.has(s._id))}}
function sprite(s,img,w,h){let d=img.data,r=Math.ceil(s.spriteRadius),x0=ci(s.x-r,0,w-1),x1=ci(s.x+r,0,w-1),y0=ci(s.y-r,0,h-1),y1=ci(s.y+r,0,h-1),sw=x1-x0+1,sh=y1-y0+1,cx=s.x-x0,cy=s.y-y0,c=document.createElement('canvas');c.width=sw;c.height=sh;let ctx=c.getContext('2d'),im=ctx.createImageData(sw,sh),o=im.data,rs=[],gs=[],bs=[];for(let y=0;y<sh;y++)for(let x=0;x<sw;x++)if(x<2||y<2||x>sw-3||y>sh-3){let p=((y0+y)*w+x0+x)*4;rs.push(d[p]);gs.push(d[p+1]);bs.push(d[p+2])}let br=med(rs),bg=med(gs),bb=med(bs);for(let y=0;y<sh;y++)for(let x=0;x<sw;x++){let p=((y0+y)*w+x0+x)*4,k=(y*sw+x)*4,rr=Math.max(0,d[p]-br),gg=Math.max(0,d[p+1]-bg),bbv=Math.max(0,d[p+2]-bb),L=.2126*rr+.7152*gg+.0722*bbv,dist=Math.hypot(x-cx,y-cy),fade=cl(1-dist/(r+.5),0,1),core=cl(1-dist/Math.max(2,r*.35),0,1),a=cl(((L/12)*fade*2.8)+(core*.85),0,1);if(L<.5||a<.002){o[k+3]=0;continue}o[k]=cl(rr*2.35+core*30,0,255);o[k+1]=cl(gg*2.35+core*30,0,255);o[k+2]=cl(bbv*2.35+core*30,0,255);o[k+3]=cl(a*255,0,255)}ctx.putImageData(im,0,0);return Object.assign({},s,{id:s._id,w:sw,h:sh,ax:cx,ay:cy,img:c,sp:c,phase:((s._id*2654435761)>>>0)/4294967296})}
async function layers(reuse){if(!cache)return;let{src,bgs,det}=cache,{w,h,img,ch}=src;let c=classify(det.stars,img,w,h);prog2(reuse?'Updating moving stars':'Creating animation layers',reuse?35:75,'Building motion background');await tick();let mm=mkMask(c.movers,w,h),motion=toCanvas(fill(ch,mm,bgs,w,h),w,h);prog2(reuse?'Updating moving stars':'Creating animation layers',reuse?75:92,'Building clean star sprites');await tick();let movers=c.movers.map(s=>sprite(s,img,w,h)),supp=c.statics.slice(0,900).map(s=>sprite(s,img,w,h));Object.assign(S,{starless:cache.fullStarless,mask:{canvas:cache.fullMask},stars:c.all,statics:supp,movers,suppressedStars:supp,motionBg:motion,motionMask:{canvas:maskCanvas(mm,w,h)},map:1,has:1,spriteFixKey:''});let b=$('build'),p=$('play'),e=$('export'),s=$('stats');if(b){b.disabled=false;b.textContent='Re-extract Stars'}if(p)p.disabled=false;if(e)e.disabled=false;if(s){s.style.display='block';s.textContent=`Detected ${det.stars.length} stars · using ${c.all.length} · moving ${movers.length} · static/protected ${c.statics.length}`}end();r();say(`Stars extracted · ${movers.length} moving · ${c.statics.length} static/protected`)}
async function dsdBuild(){if(!S||!S.src){say('Load an image first');return}try{read&&read()}catch(e){}let b=$('build'),p=$('play'),e=$('export');if(b){b.disabled=true;b.textContent='Extracting Stars…'}if(p)p.disabled=true;if(e)e.disabled=true;try{prog2('Extracting stars',5,'Reading image');await tick();let src=canvasData(S.src),{w,h,L,ch}=src;prog2('Extracting stars',20,'Estimating smooth background');await tick();let LB=background(L,w,h),res=new Float32Array(w*h),bgs=ch.map(c=>background(c,w,h));for(let i=0;i<res.length;i++)res[i]=L[i]-LB[i];prog2('Extracting stars',40,'Detecting stars against background');await tick();let n=noise(res),det={stars:detect(res,w,h,n),noise:n};prog2('Extracting stars',60,`Detected ${det.stars.length} candidates`);await tick();let cls=classify(det.stars,src.img,w,h),fullM=mkMask(cls.all,w,h);prog2('Extracting stars',68,'Creating starless diagnostic');await tick();cache={src,bgs,det,fullMask:maskCanvas(fullM,w,h),fullStarless:toCanvas(fill(ch,fullM,bgs,w,h),w,h)};await layers(false)}catch(err){console.error(err);if(b){b.disabled=false;b.textContent='Extract Stars'}end();say('Star extraction failed. Try a smaller image or lower Max Stars.')}}
async function reselect(){if(!cache)return dsdBuild();await layers(true)}
function install(){try{build=dsdBuild}catch(e){}window.build=dsdBuild;window.DSD_RESELECT_MOVERS=reselect;window.StarEngine={version:V,rebuild:dsdBuild}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();install();
})();
